const express=require('express');const http=require('http');const crypto=require('crypto');const {Server}=require('socket.io');const {Pool}=require('pg');
const app=express(),server=http.createServer(app),io=new Server(server);const PORT=process.env.PORT||3000;
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false}}):null;
const localFile=require('path').join(__dirname,'data','quizzes.json');const fs=require('fs');fs.mkdirSync(require('path').dirname(localFile),{recursive:true});if(!fs.existsSync(localFile))fs.writeFileSync(localFile,'{}');
const rooms=new Map();const id=n=>crypto.randomBytes(Math.ceil(n/2)).toString('hex').slice(0,n);
async function init(){if(pool){await pool.query(`CREATE TABLE IF NOT EXISTS quizzes(id TEXT PRIMARY KEY,title TEXT NOT NULL,theme JSONB NOT NULL DEFAULT '{}',questions JSONB NOT NULL,owner_token TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now())`)} }
async function getQuiz(qid){if(pool){const r=await pool.query('SELECT id,title,theme,questions,owner_token AS "ownerToken",created_at AS "createdAt",updated_at AS "updatedAt" FROM quizzes WHERE id=$1',[qid]);return r.rows[0]||null}const d=JSON.parse(fs.readFileSync(localFile));return d[qid]||null}
async function saveQuiz(q){if(pool){await pool.query(`INSERT INTO quizzes(id,title,theme,questions,owner_token) VALUES($1,$2,$3,$4,$5) ON CONFLICT(id) DO UPDATE SET title=$2,theme=$3,questions=$4,updated_at=now()`,[q.id,q.title,JSON.stringify(q.theme||{}),JSON.stringify(q.questions||[]),q.ownerToken])}else{const d=JSON.parse(fs.readFileSync(localFile));d[q.id]=q;fs.writeFileSync(localFile,JSON.stringify(d,null,2))}}
async function deleteQuiz(qid){if(pool)await pool.query('DELETE FROM quizzes WHERE id=$1',[qid]);else{const d=JSON.parse(fs.readFileSync(localFile));delete d[qid];fs.writeFileSync(localFile,JSON.stringify(d,null,2))}}
app.use(express.json({limit:'5mb'}));app.use(express.static(require('path').join(__dirname,'public')));
app.get('/api/quiz/:id',async(req,res)=>{const q=await getQuiz(req.params.id);if(!q)return res.status(404).json({error:'Quiz not found'});const {ownerToken,...pub}=q;res.json(pub)});
app.get('/api/manage/:id/:token',async(req,res)=>{const q=await getQuiz(req.params.id);if(!q)return res.status(404).json({error:'Quiz not found'});if(req.params.token!==q.ownerToken)return res.status(403).json({error:'관리 링크가 올바르지 않습니다.'});const {ownerToken,...pub}=q;res.json(pub)});
app.post('/api/quizzes',async(req,res)=>{try{const b=req.body||{};if(!b.title||!Array.isArray(b.questions)||!b.questions.length)return res.status(400).json({error:'Title and questions are required.'});const q={id:id(10),title:String(b.title).slice(0,120),theme:b.theme||{},questions:b.questions,ownerToken:id(32)};await saveQuiz(q);res.json({id:q.id,ownerToken:q.ownerToken})}catch(e){console.error('CREATE QUIZ ERROR',e);res.status(500).json({error:'퀴즈 저장 중 서버 오류가 발생했습니다.'})}});
app.put('/api/quizzes/:id',async(req,res)=>{try{const q=await getQuiz(req.params.id);if(!q)return res.status(404).json({error:'Quiz not found'});if(req.headers['x-owner-token']!==q.ownerToken)return res.status(403).json({error:'Only the creator can edit this quiz.'});q.title=String(req.body.title||q.title).slice(0,120);q.theme=req.body.theme||q.theme;q.questions=Array.isArray(req.body.questions)?req.body.questions:q.questions;await saveQuiz(q);res.json({ok:true})}catch(e){console.error('UPDATE QUIZ ERROR',e);res.status(500).json({error:'퀴즈 수정 저장 중 서버 오류가 발생했습니다.'})}});
app.delete('/api/quizzes/:id',async(req,res)=>{const q=await getQuiz(req.params.id);if(!q)return res.status(404).json({error:'Quiz not found'});if(req.headers['x-owner-token']!==q.ownerToken)return res.status(403).json({error:'Only the creator can delete this quiz.'});await deleteQuiz(q.id);res.json({ok:true})});
app.post('/api/rooms',async(req,res)=>{const q=await getQuiz(req.body.quizId);if(!q)return res.status(404).json({error:'Quiz not found'});let code;do code=String(Math.floor(100000+Math.random()*900000));while(rooms.has(code));rooms.set(code,{code,quizId:q.id,hostId:null,phase:'lobby',questionIndex:-1,startedAt:null,participants:new Map(),answers:new Map(),nextTimer:null,revealTimer:null});res.json({code})});
function pubQ(q){return {type:q.type,prompt:q.prompt,options:q.options||[],imageUrl:q.imageUrl||'',videoId:q.videoId||'',audioUrl:q.audioUrl||'',audioName:q.audioName||'',start:+(q.start||0),end:+(q.end||0),showVideo:q.showVideo!==false,colors:Array.isArray(q.colors)?q.colors:[],timeLimit:Math.max(1,+(q.timeLimit||15)),revealEnabled:q.revealEnabled!==false,revealSeconds:Math.max(0,+(q.revealSeconds||5)),fever:!!q.fever,platinum:!!q.platinum,allowAnswerChange:!!q.allowAnswerChange,waitFullTime:q.waitFullTime!==false}};
function snapshot(r,q){const qu=r.questionIndex>=0?q.questions[r.questionIndex]:null;const answerCounts=(qu&&Array.isArray(qu.options))?qu.options.map((o,i)=>[...r.answers.values()].reduce((n,a)=>{const vals=Array.isArray(a.answer)?a.answer:[a.answer];return n+(vals.some(v=>norm(v)===norm(o))?1:0)},0)):[];return {code:r.code,title:q.title,phase:r.phase,questionIndex:r.questionIndex,totalQuestions:q.questions.length,answerCounts,answeredCount:r.answers.size,participants:[...r.participants.values()].map(p=>({id:p.id,nickname:p.nickname,score:p.score,answered:r.answers.has(p.id)}))}};
async function broadcast(r){const q=await getQuiz(r.quizId);if(q)io.to(r.code).emit('room:state',snapshot(r,q))}
async function finish(r){const q=await getQuiz(r.quizId);r.phase='finished';const results=[...r.participants.values()].sort((a,b)=>b.score-a.score).map((p,i)=>({rank:i+1,nickname:p.nickname,score:p.score,id:p.id}));io.to(r.code).emit('game:finished',{title:q.title,results});broadcast(r)}
async function reveal(r){const q=await getQuiz(r.quizId);if(!q||r.phase!=='question')return;const qu=q.questions[r.questionIndex];const idx=r.questionIndex;r.phase='reveal';
// v4: NEVER make the participant infer submission state from event timing.
// The reveal packet itself contains that player's authoritative server-side result.
// Each participant gets a private packet; nobody receives another player's result.
for(const p of r.participants.values()){
  const a=r.answers.get(p.id);
  io.to(p.id).emit('question:reveal',{index:idx,correctAnswer:qu.answer,question:pubQ(qu),submitted:!!a,playerResult:a?{correct:!!a.correct,points:+(a.points||0),answer:a.answer}:null});
}
if(r.hostId)io.to(r.hostId).emit('host:answers',[...r.answers.entries()].map(([playerId,a])=>({playerId,nickname:r.participants.get(playerId)?.nickname||'Player',...a})));
broadcast(r);clearTimeout(r.revealTimer);r.revealTimer=setTimeout(async()=>{if(r.questionIndex+1<q.questions.length){r.phase='between';io.to(r.code).emit('question:nextPreview',{index:r.questionIndex+1,total:q.questions.length,question:pubQ(q.questions[r.questionIndex+1])});broadcast(r);r.revealTimer=setTimeout(()=>startQuestion(r),3000)}else finish(r)},Math.max(0,+(qu.revealSeconds||5))*1000)}
async function startQuestion(r){const q=await getQuiz(r.quizId);r.questionIndex++;if(r.questionIndex>=q.questions.length)return finish(r);r.phase='question';r.answers=new Map();r.startedAt=Date.now();const qu=q.questions[r.questionIndex];io.to(r.code).emit('question:start',{index:r.questionIndex,total:q.questions.length,question:pubQ(qu),startedAt:r.startedAt});broadcast(r);clearTimeout(r.nextTimer);r.nextTimer=setTimeout(()=>reveal(r),Math.max(1,+(qu.timeLimit||15))*1000)}
function norm(v){return String(v??'').trim().toLowerCase().replace(/\s+/g,' ')}function correct(q,a){if(q.type==='multiple'){return JSON.stringify((Array.isArray(a)?a:[a]).map(norm).sort())===JSON.stringify((Array.isArray(q.answer)?q.answer:[q.answer]).map(norm).sort())}if(q.type==='ordering')return JSON.stringify(a||[])===JSON.stringify(q.answer||[]);if(q.type==='subjective')return (Array.isArray(q.answer)?q.answer:[q.answer]).map(norm).includes(norm(a));return norm(a)===norm(q.answer)}
async function syncPlayer(s,r){const q=await getQuiz(r.quizId);if(!q)return;if(r.phase==='question'&&r.questionIndex>=0){s.emit('question:start',{index:r.questionIndex,total:q.questions.length,question:pubQ(q.questions[r.questionIndex]),startedAt:r.startedAt});if(r.answers.has(s.id))s.emit('answer:locked',{ok:true,changed:false})}else if(r.phase==='reveal'&&r.questionIndex>=0){const qu=q.questions[r.questionIndex];const a=r.answers.get(s.id);s.emit('question:reveal',{index:r.questionIndex,correctAnswer:qu.answer,question:pubQ(qu),submitted:!!a,playerResult:a?{correct:!!a.correct,points:+(a.points||0),answer:a.answer}:null})}else if(r.phase==='between'&&r.questionIndex+1<q.questions.length){s.emit('question:nextPreview',{index:r.questionIndex+1,total:q.questions.length,question:pubQ(q.questions[r.questionIndex+1])})}else if(r.phase==='finished'){const results=[...r.participants.values()].sort((a,b)=>b.score-a.score).map((p,i)=>({rank:i+1,nickname:p.nickname,score:p.score,id:p.id}));s.emit('game:finished',{title:q.title,results})}}
io.on('connection',s=>{s.on('host:join',async({code})=>{const r=rooms.get(String(code));if(!r)return s.emit('error:msg','방을 찾을 수 없습니다.');r.hostId=s.id;s.join(r.code);s.data.roomCode=r.code;s.data.host=true;const q=await getQuiz(r.quizId);s.emit('host:joined',snapshot(r,q));if(r.phase==='question'&&r.questionIndex>=0)s.emit('question:start',{index:r.questionIndex,total:q.questions.length,question:pubQ(q.questions[r.questionIndex]),startedAt:r.startedAt});s.emit('host:answers',[...r.answers.entries()].map(([playerId,a])=>({playerId,nickname:r.participants.get(playerId)?.nickname||'Player',...a})));broadcast(r)});
s.on('player:join',async({code,nickname,reconnectToken})=>{
 const r=rooms.get(String(code));
 if(!r)return s.emit('error:msg','방을 찾을 수 없습니다.');
 let existing=null;
 if(reconnectToken)existing=[...r.participants.values()].find(p=>p.reconnectToken===reconnectToken);
 if(existing){
  const oldId=existing.id; existing.id=s.id; existing.disconnectedAt=null;
  r.participants.delete(oldId); r.participants.set(s.id,existing);
  if(r.answers.has(oldId)){const a=r.answers.get(oldId);r.answers.delete(oldId);r.answers.set(s.id,a)}
  s.data.reconnectToken=reconnectToken;s.data.roomCode=r.code;s.data.host=false;s.join(r.code);
  s.emit('player:joined',{code:r.code,nickname:existing.nickname,title:(await getQuiz(r.quizId)).title,reconnected:true,score:existing.score,reconnectToken});
  broadcast(r);await syncPlayer(s,r);return;
 }
 if(r.participants.size>=32)return s.emit('error:msg','최대 32명까지 참가할 수 있습니다.');
 const token=id(24),p={id:s.id,nickname:String(nickname||'Player').trim().slice(0,20)||'Player',score:0,reconnectToken:token,disconnectedAt:null};
 r.participants.set(s.id,p);s.join(r.code);s.data.roomCode=r.code;s.data.reconnectToken=token;
 s.emit('player:joined',{code:r.code,nickname:p.nickname,title:(await getQuiz(r.quizId)).title,reconnectToken:token});
 broadcast(r);await syncPlayer(s,r);
});
s.on('host:start',()=>{const r=rooms.get(s.data.roomCode);if(r&&s.data.host&&r.phase==='lobby')startQuestion(r)});
s.on('player:answer',async({answer},ack)=>{const reply=(v)=>{if(typeof ack==='function')ack(v)};const r=rooms.get(s.data.roomCode);if(!r||r.phase!=='question'||!r.participants.has(s.id))return reply({ok:false,error:'문제가 이미 종료되었습니다.'});const q=(await getQuiz(r.quizId)).questions[r.questionIndex];const old=r.answers.get(s.id);if(old&&!q.allowAnswerChange)return reply({ok:false,error:'이미 제출한 답안입니다.'});const elapsed=Date.now()-r.startedAt,limit=Math.max(1,+(q.timeLimit||15))*1000;if(elapsed>=limit)return reply({ok:false,error:'제출 시간이 종료되었습니다.'});const is=correct(q,answer);let points=0;if(is){const ratio=Math.max(0,1-Math.min(elapsed,limit)/limit);points=Math.round((500+500*ratio)*(q.platinum?3:q.fever?2:q.fever?2:1))}if(old)r.participants.get(s.id).score-=old.points||0;r.answers.set(s.id,{answer,correct:is,points,elapsed});r.participants.get(s.id).score+=points;reply({ok:true,changed:!!old});s.emit('answer:locked',{ok:true,changed:!!old});if(r.hostId)io.to(r.hostId).emit('host:answers',[...r.answers.entries()].map(([playerId,a])=>({playerId,nickname:r.participants.get(playerId)?.nickname||'Player',...a})));broadcast(r);if(!q.waitFullTime&&r.answers.size>=r.participants.size&&r.participants.size>0){clearTimeout(r.nextTimer);reveal(r)}});
s.on('disconnect',()=>{const r=rooms.get(s.data.roomCode);if(!r)return;if(r.hostId===s.id){io.to(r.code).emit('error:msg','주최자가 나가서 방이 종료되었습니다.');rooms.delete(r.code);return}const p=r.participants.get(s.id);if(p){p.disconnectedAt=Date.now();setTimeout(()=>{const cur=r.participants.get(s.id);if(cur&&cur.disconnectedAt&&Date.now()-cur.disconnectedAt>=60000){r.participants.delete(s.id);r.answers.delete(s.id);broadcast(r)}},60000)}broadcast(r)})});
app.use((req,res)=>res.sendFile(require('path').join(__dirname,'public','index.html')));
init().then(()=>server.listen(PORT,'0.0.0.0',()=>console.log('QUIZ LIVE ONLINE on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
