const express=require('express');const http=require('http');const crypto=require('crypto');const path=require('path');const {Server}=require('socket.io');const {Pool}=require('pg');const multer=require('multer');const QRCode=require('qrcode');
const app=express(),server=http.createServer(app),io=new Server(server,{maxHttpBufferSize:2*1024*1024});const PORT=process.env.PORT||3000;
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false}}):null;
const fs=require('fs');const localFile=path.join(__dirname,'data','quizzes.json');const uploadDir=path.join(__dirname,'uploads');fs.mkdirSync(path.dirname(localFile),{recursive:true});fs.mkdirSync(uploadDir,{recursive:true});if(!fs.existsSync(localFile))fs.writeFileSync(localFile,'{}');
const rooms=new Map();const id=n=>crypto.randomBytes(Math.ceil(n/2)).toString('hex').slice(0,n);
const DEFAULT_OPTION_COLORS=['#e84855','#f4b942','#2e9de0','#8b5cf6','#22c55e','#f97316','#ec4899','#06b6d4'];
const playerFile=path.join(__dirname,'data','players.json');if(!fs.existsSync(playerFile))fs.writeFileSync(playerFile,'{}');
function makePlayer(){return {id:id(24),xp:0,level:1,matches:0,wins:0,correct:0,answered:0,totalQuestions:0,bestScore:0,maxCombo:0,recoveryCodeHash:'',recoveryCodeLast4:'',createdAt:Date.now(),updatedAt:Date.now()}}
function loadPlayers(){try{return JSON.parse(fs.readFileSync(playerFile,'utf8'))}catch{return {}}}
function savePlayers(d){fs.writeFileSync(playerFile,JSON.stringify(d,null,2))}
function hashRecoveryCode(code){return crypto.createHash('sha256').update(String(code||'')).digest('hex')}
function makeRecoveryCode(){return `${id(4).toUpperCase()}-${id(4).toUpperCase()}-${id(4).toUpperCase()}`}
async function getPlayer(pid){if(!pid)return null;if(pool){const r=await pool.query('SELECT id,xp,level,matches,wins,correct,answered,total_questions AS "totalQuestions",best_score AS "bestScore",max_combo AS "maxCombo",recovery_code_hash AS "recoveryCodeHash",recovery_code_last4 AS "recoveryCodeLast4",created_at AS "createdAt",updated_at AS "updatedAt" FROM players WHERE id=$1',[pid]);return r.rows[0]||null}return loadPlayers()[pid]||null}
async function ensurePlayer(pid){let p=await getPlayer(pid);if(p)return p;const base=makePlayer();base.id=pid||base.id;if(pool){await pool.query('INSERT INTO players(id,xp,level,matches,wins,correct,answered,total_questions,best_score,max_combo,recovery_code_hash,recovery_code_last4) VALUES($1,0,1,0,0,0,0,0,0,0,\'\',\'\')',[base.id])}else{const d=loadPlayers();d[base.id]=base;savePlayers(d)}return base}
function publicProfile(p){return {id:p.id,xp:p.xp||0,level:p.level||1,matches:p.matches||0,wins:p.wins||0,correct:p.correct||0,answered:p.answered||0,totalQuestions:p.totalQuestions||0,bestScore:p.bestScore||0,maxCombo:p.maxCombo||0,recoveryCodeLast4:p.recoveryCodeLast4||''}}
async function issueRecoveryCode(pid){const code=makeRecoveryCode(),hash=hashRecoveryCode(code),last4=code.slice(-4);if(pool){await pool.query('UPDATE players SET recovery_code_hash=$2,recovery_code_last4=$3,updated_at=now() WHERE id=$1',[pid,hash,last4])}else{const d=loadPlayers();if(!d[pid])return null;d[pid].recoveryCodeHash=hash;d[pid].recoveryCodeLast4=last4;d[pid].updatedAt=Date.now();savePlayers(d)}return code}
async function recoverPlayerByCode(code){const hash=hashRecoveryCode(String(code||'').trim().toUpperCase());if(pool){const r=await pool.query('SELECT id,xp,level,matches,wins,correct,answered,total_questions AS "totalQuestions",best_score AS "bestScore",max_combo AS "maxCombo",recovery_code_hash AS "recoveryCodeHash",recovery_code_last4 AS "recoveryCodeLast4",created_at AS "createdAt",updated_at AS "updatedAt" FROM players WHERE recovery_code_hash=$1',[hash]);return r.rows[0]||null}const d=loadPlayers();return Object.values(d).find(x=>x&&x.recoveryCodeHash===hash)||null}
async function recordMatch(r,q,results){const matchId=id(20),now=Date.now();const match={id:matchId,quizId:q.id,title:q.title,mode:r.mode||q.mode||'normal',startedAt:r.startedAt||now,finishedAt:now,playerCount:results.length};if(pool){await pool.query('INSERT INTO matches(id,quiz_id,title,mode,started_at,finished_at,player_count) VALUES($1,$2,$3,$4,to_timestamp($5/1000.0),to_timestamp($6/1000.0),$7)',[match.id,match.quizId,match.title,match.mode,match.startedAt,match.finishedAt,match.playerCount]);for(const x of results){const pid=x.playerId;if(!pid)continue;await pool.query('INSERT INTO match_players(match_id,player_id,score,rank,correct_count,answered,total_questions,accuracy,avg_response_ms,max_combo,team,eliminated) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)',[match.id,pid,x.score,x.rank,x.correctCount,x.answered,x.totalQuestions,x.accuracy,x.avgResponseMs,x.maxCombo,x.team,x.eliminated]);await pool.query('UPDATE players SET xp=xp+$2,level=GREATEST(1,FLOOR((xp+$2)/1000)+1),matches=matches+1,wins=wins+$3,correct=correct+$4,answered=answered+$5,total_questions=total_questions+$6,best_score=GREATEST(best_score,$7),max_combo=GREATEST(max_combo,$8),updated_at=now() WHERE id=$1',[pid,Math.max(10,Math.round(x.score/10)+x.correctCount*5),x.rank===1&&!r.noWinner?1:0,x.correctCount,x.answered,x.totalQuestions,x.score,x.maxCombo||0])}}else{const d=loadPlayers();d.__matches=d.__matches||{};d.__matches[match.id]={...match,results};for(const x of results){if(!x.playerId)continue;const p=d[x.playerId]||makePlayer();p.id=x.playerId;p.xp=(p.xp||0)+Math.max(10,Math.round(x.score/10)+x.correctCount*5);p.level=Math.floor(p.xp/1000)+1;p.matches=(p.matches||0)+1;p.wins=(p.wins||0)+((x.rank===1&&!r.noWinner)?1:0);p.correct=(p.correct||0)+x.correctCount;p.answered=(p.answered||0)+x.answered;p.totalQuestions=(p.totalQuestions||0)+x.totalQuestions;p.bestScore=Math.max(p.bestScore||0,x.score||0);p.maxCombo=Math.max(p.maxCombo||0,x.maxCombo||0);p.updatedAt=now;d[x.playerId]=p}savePlayers(d)}return matchId}

async function init(){if(pool){await pool.query(`CREATE TABLE IF NOT EXISTS quizzes(id TEXT PRIMARY KEY,title TEXT NOT NULL,theme JSONB NOT NULL DEFAULT '{}',questions JSONB NOT NULL,owner_token TEXT NOT NULL,mode TEXT NOT NULL DEFAULT 'normal',combo_enabled BOOLEAN NOT NULL DEFAULT false,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now())`);await pool.query(`ALTER TABLE quizzes ADD COLUMN IF NOT EXISTS mode TEXT NOT NULL DEFAULT 'normal'`);await pool.query(`ALTER TABLE quizzes ADD COLUMN IF NOT EXISTS combo_enabled BOOLEAN NOT NULL DEFAULT false`);await pool.query(`CREATE TABLE IF NOT EXISTS players(id TEXT PRIMARY KEY,nickname TEXT NOT NULL,avatar TEXT NOT NULL DEFAULT '🦊',xp INTEGER NOT NULL DEFAULT 0,level INTEGER NOT NULL DEFAULT 1,matches INTEGER NOT NULL DEFAULT 0,wins INTEGER NOT NULL DEFAULT 0,correct INTEGER NOT NULL DEFAULT 0,answered INTEGER NOT NULL DEFAULT 0,total_questions INTEGER NOT NULL DEFAULT 0,best_score INTEGER NOT NULL DEFAULT 0,max_combo INTEGER NOT NULL DEFAULT 0,recovery_code_hash TEXT NOT NULL DEFAULT '',recovery_code_last4 TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now())`);await pool.query(`ALTER TABLE players ADD COLUMN IF NOT EXISTS recovery_code_hash TEXT NOT NULL DEFAULT ''`);await pool.query(`ALTER TABLE players ADD COLUMN IF NOT EXISTS recovery_code_last4 TEXT NOT NULL DEFAULT ''`);await pool.query(`CREATE TABLE IF NOT EXISTS matches(id TEXT PRIMARY KEY,quiz_id TEXT,title TEXT,mode TEXT,started_at TIMESTAMPTZ,finished_at TIMESTAMPTZ,player_count INTEGER)`);await pool.query(`CREATE TABLE IF NOT EXISTS match_players(match_id TEXT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,player_id TEXT NOT NULL REFERENCES players(id) ON DELETE CASCADE,score INTEGER NOT NULL DEFAULT 0,rank INTEGER,correct_count INTEGER NOT NULL DEFAULT 0,answered INTEGER NOT NULL DEFAULT 0,total_questions INTEGER NOT NULL DEFAULT 0,accuracy INTEGER NOT NULL DEFAULT 0,avg_response_ms INTEGER NOT NULL DEFAULT 0,max_combo INTEGER NOT NULL DEFAULT 0,team TEXT,eliminated BOOLEAN NOT NULL DEFAULT false,PRIMARY KEY(match_id,player_id))`)} }
async function getQuiz(qid){let q;if(pool){const r=await pool.query('SELECT id,title,theme,questions,owner_token AS "ownerToken",mode,combo_enabled AS "comboEnabled",created_at AS "createdAt",updated_at AS "updatedAt" FROM quizzes WHERE id=$1',[qid]);q=r.rows[0]||null}else{const d=JSON.parse(fs.readFileSync(localFile));q=d[qid]||null}if(q){q=await migrateLegacyAudio(q);q=await migrateLegacyImages(q)}return q}
async function saveQuiz(q){if(pool){await pool.query(`INSERT INTO quizzes(id,title,theme,questions,owner_token,mode,combo_enabled) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO UPDATE SET title=$2,theme=$3,questions=$4,mode=$6,combo_enabled=$7,updated_at=now()`,[q.id,q.title,JSON.stringify(q.theme||{}),JSON.stringify(q.questions||[]),q.ownerToken,q.mode||'normal',!!q.comboEnabled])}else{const d=JSON.parse(fs.readFileSync(localFile));d[q.id]=q;fs.writeFileSync(localFile,JSON.stringify(d,null,2))}}
async function deleteQuiz(qid){if(pool)await pool.query('DELETE FROM quizzes WHERE id=$1',[qid]);else{const d=JSON.parse(fs.readFileSync(localFile));delete d[qid];fs.writeFileSync(localFile,JSON.stringify(d,null,2))}}
function normalizeQuizServer(q){if(!q||typeof q!=='object')return q;if(q.mode==='survival')q.mode='death';q.mode=['normal','death','speedrun','team'].includes(q.mode)?q.mode:'normal';q.comboEnabled=q.mode==='speedrun'?false:!!q.comboEnabled;for(const x of q.questions||[]){if(q.mode==='speedrun'){x.highRisk=false;x.raidEnabled=false;x.waitFullTime=false}else if(q.mode==='team'){x.raidEnabled=false}else if(q.mode==='death'){x.highRisk=false;x.raidEnabled=false}if(x.raidEnabled&&x.highRisk)x.highRisk=false;if(x.raidEnabled&&q.mode==='normal'){x.type='choice';x.options=Array.from({length:8},(_,i)=>x.options?.[i]||'');x.colors=Array.from({length:8},(_,i)=>x.colors?.[i]||DEFAULT_OPTION_COLORS[i])}else if(!x.raidEnabled&&x.type==='choice'&&(x.options||[]).length>4){x.options=Array.from({length:4},(_,i)=>x.options?.[i]||'');x.colors=Array.isArray(x.colors)?x.colors.slice(0,4):x.colors;if(Array.isArray(x.answer))x.answer=x.answer[0]||''}}return q}
const MAX_AUDIO_BYTES=20*1024*1024;const MAX_IMAGE_BYTES=5*1024*1024;
function dataUrlBytes(v){if(typeof v!=='string'||!v.startsWith('data:'))return 0;const i=v.indexOf(',');if(i<0)return 0;const meta=v.slice(5,i);const body=v.slice(i+1);if(/;base64/i.test(meta))return Math.floor(body.length*3/4)-((body.endsWith('==')?2:body.endsWith('=')?1:0));return new TextEncoder().encode(decodeURIComponent(body)).length}
function validateQuizMedia(questions){for(const q of questions||[]){if(q.audioUrl&&String(q.audioUrl).startsWith('data:')){const bytes=dataUrlBytes(q.audioUrl);if(bytes>MAX_AUDIO_BYTES)return '음악 파일은 문제당 최대 20MB까지 사용할 수 있습니다.';if(!/^data:audio\//i.test(q.audioUrl))return '음악 파일 형식이 올바르지 않습니다.';}}return null}

function safeAudioExt(originalName,mime){const ext=path.extname(originalName||'').toLowerCase();const allowed={'.mp3':'audio/mpeg','.wav':'audio/wav','.m4a':'audio/mp4','.ogg':'audio/ogg','.oga':'audio/ogg','.webm':'audio/webm','.aac':'audio/aac','.flac':'audio/flac'};return allowed[ext]===mime?ext:(mime==='audio/mpeg'?'.mp3':mime==='audio/wav'?'.wav':mime==='audio/mp4'?'.m4a':mime==='audio/ogg'?'.ogg':mime==='audio/webm'?'.webm':'.bin')}
function writeDataUrlAudio(dataUrl,name){if(typeof dataUrl!=='string'||!/^data:audio\//i.test(dataUrl))return null;const comma=dataUrl.indexOf(',');if(comma<0)return null;const meta=dataUrl.slice(5,comma),body=dataUrl.slice(comma+1);const mime=(meta.split(';')[0]||'audio/mpeg').toLowerCase();const buf=/;base64/i.test(meta)?Buffer.from(body,'base64'):Buffer.from(decodeURIComponent(body),'utf8');if(buf.length>MAX_AUDIO_BYTES)throw Object.assign(new Error('audio too large'),{code:'LIMIT_FILE_SIZE'});const filename=id(24)+safeAudioExt(name,mime);fs.writeFileSync(path.join(uploadDir,filename),buf);return '/uploads/'+filename}
async function migrateLegacyAudio(q){let changed=false;for(const item of q.questions||[]){if(item.audioUrl&&String(item.audioUrl).startsWith('data:audio/')){const url=writeDataUrlAudio(item.audioUrl,item.audioName||'audio.mp3');if(url){item.audioUrl=url;changed=true}}}if(changed)await saveQuiz(q);return q}

function safeImageExt(originalName,mime){const ext=path.extname(originalName||'').toLowerCase();const allowed={'.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp','.gif':'image/gif'};return allowed[ext]===mime?ext:(mime==='image/png'?'.png':mime==='image/webp'?'.webp':mime==='image/gif'?'.gif':'.jpg')}
const imageStorage=multer.diskStorage({destination:(req,file,cb)=>cb(null,uploadDir),filename:(req,file,cb)=>cb(null,id(24)+safeImageExt(file.originalname,file.mimetype))});
const uploadImage=multer({storage:imageStorage,limits:{fileSize:MAX_IMAGE_BYTES},fileFilter:(req,file,cb)=>cb(null,/^image\/(jpeg|png|webp|gif)$/i.test(file.mimetype))});
function writeDataUrlImage(dataUrl,name){if(typeof dataUrl!=='string'||!/^data:image\//i.test(dataUrl))return null;const comma=dataUrl.indexOf(',');if(comma<0)return null;const meta=dataUrl.slice(5,comma),body=dataUrl.slice(comma+1),mime=(meta.split(';')[0]||'image/jpeg').toLowerCase();const buf=/;base64/i.test(meta)?Buffer.from(body,'base64'):Buffer.from(decodeURIComponent(body),'utf8');if(buf.length>MAX_IMAGE_BYTES)throw Object.assign(new Error('image too large'),{code:'LIMIT_FILE_SIZE'});const filename=id(24)+safeImageExt(name,mime);fs.writeFileSync(path.join(uploadDir,filename),buf);return '/uploads/'+filename}
async function migrateLegacyImages(q){let changed=false;for(const item of q.questions||[]){if(item.imageUrl&&String(item.imageUrl).startsWith('data:image/')){const url=writeDataUrlImage(item.imageUrl,item.imageName||'image.jpg');if(url){item.imageUrl=url;item.imageName=item.imageName||'legacy image';changed=true}}}if(q.theme&&q.theme.background&&String(q.theme.background).startsWith('data:image/')){const url=writeDataUrlImage(q.theme.background,'background.jpg');if(url){q.theme.background=url;changed=true}}if(changed)await saveQuiz(q);return q}

const audioStorage=multer.diskStorage({destination:(req,file,cb)=>cb(null,uploadDir),filename:(req,file,cb)=>cb(null,id(24)+safeAudioExt(file.originalname,file.mimetype))});
const uploadAudio=multer({storage:audioStorage,limits:{fileSize:MAX_AUDIO_BYTES},fileFilter:(req,file,cb)=>cb(null,/^audio\//i.test(file.mimetype))});
app.use(express.json({limit:'120mb'}));
app.use((err,req,res,next)=>{if(err&&err.type==='entity.too.large')return res.status(413).json({error:'퀴즈 저장 데이터가 너무 큽니다. 음악 파일은 문제당 20MB 이하로 사용하고, 전체 퀴즈 크기를 줄여주세요.'});if(err)return res.status(400).json({error:'퀴즈 데이터 형식이 올바르지 않습니다.'});next(err)});
app.use(express.static(path.join(__dirname,'public')));app.use('/uploads',express.static(uploadDir));
app.post('/api/upload-audio',uploadAudio.single('audio'),(req,res)=>{if(!req.file)return res.status(400).json({error:'음악 파일을 선택해주세요.'});res.json({ok:true,url:'/uploads/'+req.file.filename,name:req.file.originalname,size:req.file.size,mime:req.file.mimetype})});
app.post('/api/upload-image',uploadImage.single('image'),(req,res)=>{if(!req.file)return res.status(400).json({error:'이미지 파일을 선택해주세요.'});res.json({ok:true,url:'/uploads/'+req.file.filename,name:req.file.originalname,size:req.file.size,mime:req.file.mimetype})});
app.get('/api/room/:code/qr',async(req,res)=>{try{const r=rooms.get(String(req.params.code));if(!r)return res.status(404).send('Not found');const proto=req.get('x-forwarded-proto')||req.protocol;const joinUrl=`${proto}://${req.get('host')}/?room=${encodeURIComponent(r.code)}`;res.type('svg').send(await QRCode.toString(joinUrl,{type:'svg',margin:1,width:280,color:{dark:'#111827',light:'#ffffff'}}))}catch(e){res.status(500).send('QR error')}});
app.use((err,req,res,next)=>{if(err instanceof multer.MulterError&&err.code==='LIMIT_FILE_SIZE')return res.status(413).json({error:'음악 파일은 최대 20MB까지 업로드할 수 있습니다.'});if(err&&err.message==='Unexpected field')return res.status(400).json({error:'음악 업로드 요청이 올바르지 않습니다.'});if(err)return res.status(400).json({error:'파일 업로드에 실패했습니다.'});next(err)});
app.get('/api/profile/:id',async(req,res)=>{try{const p=await ensurePlayer(String(req.params.id));let profile=publicProfile(p);if(!p.recoveryCodeHash){profile.recoveryCode=await issueRecoveryCode(p.id);profile.recoveryCodeLast4=profile.recoveryCode.slice(-4)}res.json(profile)}catch(e){console.error(e);res.status(500).json({error:'프로필을 불러오지 못했습니다.'})}});
app.post('/api/profile/:id/recovery',async(req,res)=>{try{const p=await ensurePlayer(String(req.params.id));const code=await issueRecoveryCode(p.id);res.json({id:p.id,recoveryCode:code})}catch(e){console.error(e);res.status(500).json({error:'복구 코드 발급에 실패했습니다.'})}});
app.post('/api/profile/recover',async(req,res)=>{try{const code=String(req.body?.recoveryCode||'').trim().toUpperCase();if(!/^[A-Z0-9]{4}(?:-[A-Z0-9]{4}){2}$/.test(code))return res.status(400).json({error:'복구 코드 형식이 올바르지 않습니다.'});const p=await recoverPlayerByCode(code);if(!p)return res.status(404).json({error:'일치하는 프로필을 찾을 수 없습니다.'});res.json({profile:publicProfile(p)})}catch(e){console.error(e);res.status(500).json({error:'프로필 복구에 실패했습니다.'})}});
app.get('/api/quiz/:id',async(req,res)=>{const q=await getQuiz(req.params.id);if(!q)return res.status(404).json({error:'Quiz not found'});const {ownerToken,...pub}=q;res.json(pub)});
app.get('/api/manage/:id/:token',async(req,res)=>{const q=await getQuiz(req.params.id);if(!q)return res.status(404).json({error:'Quiz not found'});if(req.params.token!==q.ownerToken)return res.status(403).json({error:'관리 링크가 올바르지 않습니다.'});const {ownerToken,...pub}=q;res.json(pub)});
app.post('/api/quizzes',async(req,res)=>{try{const b=req.body||{};if(!b.title||!Array.isArray(b.questions)||!b.questions.length)return res.status(400).json({error:'Title and questions are required.'});const mediaError=validateQuizMedia(b.questions);if(mediaError)return res.status(413).json({error:mediaError});const q=normalizeQuizServer({id:id(10),title:String(b.title).slice(0,120),theme:b.theme||{},questions:b.questions,mode:b.mode,comboEnabled:b.comboEnabled,ownerToken:id(32)});await saveQuiz(q);res.json({id:q.id,ownerToken:q.ownerToken})}catch(e){console.error('CREATE QUIZ ERROR',e);res.status(500).json({error:'퀴즈 저장 중 서버 오류가 발생했습니다.'})}});
app.put('/api/quizzes/:id',async(req,res)=>{try{const q=await getQuiz(req.params.id);if(!q)return res.status(404).json({error:'Quiz not found'});if(req.headers['x-owner-token']!==q.ownerToken)return res.status(403).json({error:'Only the creator can edit this quiz.'});q.title=String(req.body.title||q.title).slice(0,120);q.theme=req.body.theme||q.theme;q.questions=Array.isArray(req.body.questions)?req.body.questions:q.questions;q.mode=req.body.mode||q.mode||'normal';q.comboEnabled=req.body.comboEnabled!==undefined?!!req.body.comboEnabled:!!q.comboEnabled;normalizeQuizServer(q);const mediaError=validateQuizMedia(q.questions);if(mediaError)return res.status(413).json({error:mediaError});await saveQuiz(q);res.json({ok:true})}catch(e){console.error('UPDATE QUIZ ERROR',e);res.status(500).json({error:'퀴즈 수정 저장 중 서버 오류가 발생했습니다.'})}});
app.delete('/api/quizzes/:id',async(req,res)=>{const q=await getQuiz(req.params.id);if(!q)return res.status(404).json({error:'Quiz not found'});if(req.headers['x-owner-token']!==q.ownerToken)return res.status(403).json({error:'Only the creator can delete this quiz.'});await deleteQuiz(q.id);res.json({ok:true})});
app.post('/api/rooms',async(req,res)=>{const q=normalizeQuizServer(await getQuiz(req.body.quizId));if(!q)return res.status(404).json({error:'Quiz not found'});let code;do code=String(Math.floor(100000+Math.random()*900000));while(rooms.has(code));rooms.set(code,{code,quizId:q.id,hostId:null,phase:'lobby',questionIndex:-1,startedAt:null,participants:new Map(),answers:new Map(),history:[],nextTimer:null,revealTimer:null,riskTimer:null,raidTimer:null,riskDeadline:null,raidDeadline:null,riskTransitioning:false,starting:false,noWinner:false,finalResults:null,matchId:null,mode:q.mode==='survival'?'death':(q.mode||'normal'),comboEnabled:q.comboEnabled!==false&&!!q.comboEnabled});res.json({code})});
function pubQ(q){return {type:q.type,prompt:q.prompt,options:q.type==='ox'?['O','X']:(q.options||[]),mode:q.mode==='survival'?'death':(q.mode||'normal'),comboEnabled:!!q.comboEnabled,imageUrl:q.imageUrl||'',videoId:q.videoId||'',audioUrl:q.audioUrl||'',audioName:q.audioName||'',start:+(q.start||0),end:+(q.end||0),showVideo:q.showVideo!==false,colors:Array.isArray(q.colors)?q.colors:[],timeLimit:Math.max(1,+(q.timeLimit||15)),revealEnabled:q.revealEnabled!==false,revealSeconds:Math.max(0,+(q.revealSeconds||5)),fever:!!q.fever,platinum:!!q.platinum,highRisk:!!q.highRisk,raidEnabled:!!q.raidEnabled,raidThresholdType:q.raidThresholdType||'count',raidThreshold:+(q.raidThreshold||2),allowAnswerChange:!!q.allowAnswerChange,waitFullTime:q.waitFullTime!==false}};
function teamStats(r){const out={red:{correct:0,total:0},blue:{correct:0,total:0}};for(const h of r.history||[]){for(const x of h.players||[]){const p=[...r.participants.values()].find(z=>z.reconnectToken===x.key);if(!p||!p.team||!x.submitted)continue;out[p.team].total++;if(x.correct)out[p.team].correct++}}return out}function snapshot(r,q){const qu=r.questionIndex>=0?q.questions[r.questionIndex]:null;const answerCounts=(qu&&Array.isArray(qu.options))?qu.options.map((o,i)=>[...r.answers.values()].reduce((n,a)=>{const vals=Array.isArray(a.answer)?a.answer:[a.answer];return n+(vals.some(v=>norm(v)===norm(o))?1:0)},0)):[];const ts=teamStats(r);const raidQs=(q.questions||[]).filter(x=>x.raidEnabled);const raidSummary=raidQs.length?raidQs.map((x,i)=>{const t=x.raidThresholdType==='percent'?`정답자 ${Math.max(1,Math.min(100,+x.raidThreshold||1))}%`: `정답자 ${Math.max(1,+x.raidThreshold||1)}명`;return `레이드 ${i+1}: ${t} 달성`}).join(' · '):'';return {code:r.code,title:q.title,theme:q.theme||{},phase:r.phase,questionIndex:r.questionIndex,totalQuestions:q.questions.length,raidRules:{enabled:raidQs.length>0,summary:raidSummary},answerCounts,answeredCount:r.answers.size,participants:[...r.participants.values()].map(p=>({id:p.id,playerId:p.playerId||null,nickname:p.nickname,avatar:p.avatar||'🦊',score:p.score,combo:p.combo||0,maxCombo:p.maxCombo||0,eliminated:!!p.eliminated,answered:r.answers.has(p.id),team:p.team||null,teamAccuracy:p.team? (ts[p.team].total?Math.round(ts[p.team].correct/ts[p.team].total*100):0):null,speedIndex:p.speedIndex||0,speedFinished:!!p.speedFinished,speedElapsed:p.speedFinished?(p.speedElapsed||0):(p.speedRunStartedAt?Date.now()-p.speedRunStartedAt:0)})),mode:r.mode||q.mode||'normal',comboEnabled:!!r.comboEnabled}};
async function broadcast(r){const q=await getQuiz(r.quizId);if(q)io.to(r.code).emit('room:state',snapshot(r,q))}
function activeParticipantCount(r){return [...r.participants.values()].filter(p=>!p.disconnectedAt&&p.id&&!p.eliminated).length}
function raidConfig(q,r){return r.mode==='normal'&&q&&q.raidEnabled&&q.type==='choice'&&Array.isArray(q.options)&&q.options.length===8}
function activeRiskPlayers(r){return [...r.participants.values()].filter(p=>!p.disconnectedAt&&!p.eliminated)}
function raidThreshold(r,q){const n=[...r.participants.values()].filter(p=>!p.disconnectedAt&&!p.eliminated).length;if((q.raidThresholdType||'count')==='percent')return Math.max(1,Math.ceil(n*Math.max(1,Math.min(100,+q.raidThreshold||1))/100));return Math.max(1,Math.min(n,+q.raidThreshold||1))}
function speedPoints(elapsed,limit,q){const safeElapsed=Math.max(0,Math.min(Number(elapsed)||0,limit));const step=Math.max(1,limit/999);const base=Math.max(1,1000-Math.floor(safeElapsed/step));return Math.round(base*(q.platinum?3:q.fever?2:1))}
function startRiskChoice(r,q){
 const qu=q?.questions?.[r.questionIndex];
 if(!qu||!qu.highRisk){r.startingTransition=false;void beginQuestion(r,q);return}
 clearTimeout(r.riskTimer);const index=r.questionIndex;const deadline=Date.now()+5000;
 r.phase='riskChoice';r.riskDeadline=deadline;r.riskTransitioning=false;
 for(const p of r.participants.values())if(!p.eliminated)p.riskChoice=null;
 io.to(r.code).emit('question:riskChoice',{index,total:q.questions.length,seconds:5,deadline,question:pubQ(qu)});void broadcast(r);
 r.riskTimer=setTimeout(()=>{
  if(r.phase!=='riskChoice'||r.questionIndex!==index||r.riskTransitioning)return;
  r.riskTransitioning=true;
  for(const p of activeRiskPlayers(r))if(!p.riskChoice)p.riskChoice='coward';
  clearTimeout(r.riskTimer);r.riskTimer=null;r.riskDeadline=null;r.phase='riskStarting';
  r.startingTransition=false;
  void beginQuestion(r,q).catch(e=>console.error('RISK TRANSITION ERROR',e));
 },5000);
}
async function startRaidIntro(r,q){
 const qu=q?.questions?.[r.questionIndex];if(!qu||!raidConfig(qu,r)){r.startingTransition=false;void beginQuestion(r,q);return}
 clearTimeout(r.raidTimer);const index=r.questionIndex;const deadline=Date.now()+7000;
 r.phase='raidIntro';r.raidDeadline=deadline;
 io.to(r.code).emit('question:raidIntro',{index,total:q.questions.length,seconds:7,deadline,question:pubQ(qu)});void broadcast(r);
 r.raidTimer=setTimeout(()=>{
  if(r.phase!=='raidIntro'||r.questionIndex!==index)return;
  clearTimeout(r.raidTimer);r.raidTimer=null;r.raidDeadline=null;r.phase='raidStarting';
  r.startingTransition=false;
  void beginQuestion(r,q).catch(e=>console.error('RAID TRANSITION ERROR',e));
 },7000);
}
async function beginQuestion(r,providedQ=null){
 const q=providedQ||await getQuiz(r.quizId);if(!q||r.phase==='finished'||r.phase==='question'||r.phase==='reveal')return;
 clearTimeout(r.riskTimer);r.riskTimer=null;clearTimeout(r.raidTimer);r.raidTimer=null;
 r.riskDeadline=null;r.raidDeadline=null;
 const qu=q.questions[r.questionIndex];if(!qu)return;
 r.phase='question';r.answers=new Map();r.startedAt=Date.now();
 for(const p of r.participants.values())if(!p.eliminated)p.riskChoice=p.riskChoice||'coward';
 io.to(r.code).emit('question:start',{index:r.questionIndex,total:q.questions.length,question:pubQ(qu)});void broadcast(r);
 clearTimeout(r.nextTimer);const idx=r.questionIndex;const delay=Math.max(1,+(qu.timeLimit||15))*1000;
 r.nextTimer=setTimeout(()=>{if(r.phase==='question'&&r.questionIndex===idx)void reveal(r).catch(e=>console.error('REVEAL TIMER ERROR',e))},delay);
}
async function startQuestion(r){
 const q=await getQuiz(r.quizId);
 if(!q||r.phase==='finished'||r.startingTransition)return;
 if(r.mode==='speedrun')return startSpeedrun(r);
 clearTimeout(r.nextTimer);clearTimeout(r.revealTimer);clearTimeout(r.riskTimer);clearTimeout(r.raidTimer);
 r.nextTimer=r.revealTimer=r.riskTimer=r.raidTimer=null;
 r.riskDeadline=null;r.raidDeadline=null;r.riskTransitioning=false;
 r.questionIndex++;
 if(r.questionIndex>=q.questions.length)return finish(r);
 const qu=q.questions[r.questionIndex];
 r.startingTransition=true;
 if(raidConfig(qu,r)){startRaidIntro(r,q);return;}
 if(r.mode!=='death'&&qu.highRisk){startRiskChoice(r,q);return;}
 r.startingTransition=false;
 await beginQuestion(r,q);
}

function startSpeedrun(r){getQuiz(r.quizId).then(q=>{r.phase='speedrun';r.startedAt=Date.now();for(const p of r.participants.values()){p.speedIndex=0;p.speedRunStartedAt=Date.now();p.speedStartedAt=p.speedRunStartedAt;p.speedHistory=[];p.speedFinished=false}if(r.hostId)io.to(r.hostId).emit('speedrun:start',{total:q.questions.length,title:q.title});for(const p of r.participants.values())sendSpeedQuestion(r,p,q);broadcast(r);});}
async function sendSpeedQuestion(r,p,q,resetClock=true){if(!p||p.eliminated||p.speedFinished)return;if(p.speedIndex>=q.questions.length){p.speedFinished=true;p.speedGoalAt=Date.now();p.speedElapsed=p.speedGoalAt-(p.speedRunStartedAt||p.speedGoalAt);io.to(p.id).emit('speedrun:goal',{score:p.score});if([...r.participants.values()].filter(x=>!x.disconnectedAt&&!x.eliminated).every(x=>x.speedFinished))return finishSpeedrun(r);broadcast(r);return}const qu=q.questions[p.speedIndex];if(!p.speedRunStartedAt)p.speedRunStartedAt=Date.now();p.speedStartedAt=Date.now();io.to(p.id).emit('speedrun:question',{index:p.speedIndex,total:q.questions.length,question:pubQ(qu),score:p.score});if(r.hostId)io.to(r.hostId).emit('speedrun:hostQuestion',{index:p.speedIndex,total:q.questions.length,question:pubQ(qu)});void broadcast(r)}async function finishSpeedrun(r){const q=await getQuiz(r.quizId);r.phase='finished';const results=[...r.participants.values()].sort((a,b)=>b.score-a.score).map((p,i)=>({rank:i+1,nickname:p.nickname,avatar:p.avatar||'🦊',score:p.score,id:p.id,correctCount:(p.speedHistory||[]).filter(x=>x.correct).length,answered:(p.speedHistory||[]).length,totalQuestions:q.questions.length,accuracy:p.speedHistory?.length?Math.round(p.speedHistory.filter(x=>x.correct).length/p.speedHistory.length*100):0,avgResponseMs:p.speedHistory?.length?Math.round(p.speedHistory.reduce((a,x)=>a+x.elapsed,0)/p.speedHistory.length):0,maxCombo:0,eliminated:false}));io.to(r.code).emit('game:finished',{title:q.title,results,history:r.history||[],mode:'speedrun',comboEnabled:false});broadcast(r)}
function maybeReveal(r,q){if(!q||(r.mode!=='speedrun'&&q.waitFullTime!==false)||r.phase!=='question')return false;const active=activeParticipantCount(r);if(active>0&&r.answers.size>=active){clearTimeout(r.nextTimer);void reveal(r);return true}return false}
async function finish(r){if(r.phase==='finished'&&r.finalResults)return r;const q=await getQuiz(r.quizId);if(!q)return;const isDeath=r.mode==='death'||r.mode==='survival';const survivors=isDeath?[...r.participants.values()].filter(p=>!p.eliminated&&!p.disconnectedAt):[];const noWinner=isDeath&&survivors.length===0;r.noWinner=noWinner;r.phase='finished';const sorted=[...r.participants.values()].sort((a,b)=>{if(isDeath){if(!!a.eliminated!==!!b.eliminated)return Number(a.eliminated)-Number(b.eliminated)}return b.score-a.score||a.nickname.localeCompare(b.nickname)});const results=sorted.map((p,i)=>{const rows=r.history.map(h=>h.players.find(x=>x.key===p.reconnectToken)).filter(Boolean);const answered=rows.filter(x=>x.submitted).length,correctCount=rows.filter(x=>x.correct).length,elapsed=rows.filter(x=>x.submitted).map(x=>x.elapsed);return {rank:noWinner?null:i+1,playerId:p.playerId||null,nickname:p.nickname,avatar:p.avatar||'🦊',score:p.score,id:p.id,team:p.team||null,correctCount,answered,totalQuestions:q.questions.length,accuracy:answered?Math.round(correctCount/answered*100):0,avgResponseMs:elapsed.length?Math.round(elapsed.reduce((a,b)=>a+b,0)/elapsed.length):0,maxCombo:p.maxCombo||0,eliminated:!!p.eliminated}});r.finalResults=results;try{r.matchId=await recordMatch(r,q,results)}catch(e){console.error('MATCH RECORD ERROR',e)}const teamResults=r.mode==='team'?{red:results.filter(x=>x.team==='red').sort((a,b)=>b.score-a.score||a.nickname.localeCompare(b.nickname)).map((x,i)=>({...x,teamRank:i+1})),blue:results.filter(x=>x.team==='blue').sort((a,b)=>b.score-a.score||a.nickname.localeCompare(b.nickname)).map((x,i)=>({...x,teamRank:i+1}))}:null;io.to(r.code).emit('game:finished',{title:q.title,results,history:r.history,mode:isDeath?'death':(r.mode||q.mode||'normal'),comboEnabled:!!r.comboEnabled,noWinner,teamResults,matchId:r.matchId});broadcast(r)}
async function reveal(r){const q=await getQuiz(r.quizId);if(!q||r.phase!=='question')return;const qu=q.questions[r.questionIndex];const idx=r.questionIndex;
const raid=raidConfig(qu,r);let raidSuccess=false;let raidCorrectCount=0;if(raid){raidCorrectCount=[...r.answers.values()].filter(a=>a.correct).length;raidSuccess=raidCorrectCount>=raidThreshold(r,qu);}
// Score is intentionally committed only at reveal time. v6.5.1 audit: points are not added during submission. During the question,
// participants see their previous total so a correct answer is never spoiled early.
for(const p of r.participants.values()){const a=r.answers.get(p.id);if(p.eliminated)continue;if(a&&!a.scoreCommitted){if(raid&&!raidSuccess){a.points=a.correct?0:-(a.basePoints||0);a.combo=0}else if(raid&&raidSuccess){if(a.correct)a.points=a.basePoints||0;else a.points=0}else if(a.correct&&r.comboEnabled){p.combo=(p.combo||0)+1;p.maxCombo=Math.max(p.maxCombo||0,p.combo);a.combo=p.combo;a.comboBonus=Math.max(0,(p.combo-1)*100);a.points=(a.basePoints||a.points||0)+a.comboBonus}else if(a){if(!a.correct&&r.comboEnabled)p.combo=0;a.combo=p.combo||0;a.comboBonus=0;a.points=a.basePoints||a.points||0}if(a)p.score+=a.points||0;a.scoreCommitted=true}}
if(r.mode==='death'){for(const p of r.participants.values()){if(p.eliminated)continue;const a=r.answers.get(p.id);if(!a||!a.correct)p.eliminated=true;if(!a||!a.correct)p.combo=0}}
r.history.push({index:idx,correctAnswer:qu.answer,players:[...r.participants.values()].map(p=>{const a=r.answers.get(p.id);return {key:p.reconnectToken,submitted:!!a,correct:!!a?.correct,elapsed:a?.elapsed||0,points:a?.points||0,basePoints:a?.basePoints||a?.points||0,combo:a?.combo||0,comboBonus:a?.comboBonus||0,eliminated:!!p.eliminated}})});
r.phase='reveal';
// The reveal packet itself contains each player's authoritative result.
for(const p of r.participants.values()){
  const a=r.answers.get(p.id);
  io.to(p.id).emit('question:reveal',{index:idx,correctAnswer:qu.answer,question:pubQ(qu),submitted:!!a,playerResult:a?{correct:!!a.correct,points:+(a.points||0),answer:a.answer}:null,raid:raid?{enabled:true,success:raidSuccess,threshold:raidThreshold(r,qu),correctCount:raidCorrectCount,leaders:raidSuccess?[...r.answers.entries()].filter(([,a])=>a.correct).sort((x,y)=>(x[1].elapsed||0)-(y[1].elapsed||0)).slice(0,raidThreshold(r,qu)).map(([pid,a])=>({nickname:r.participants.get(pid)?.nickname||'Player',avatar:r.participants.get(pid)?.avatar||'🦊',points:+(a.points||0)})):[]}:null});
}
if(r.hostId)io.to(r.hostId).emit('host:answers',[...r.answers.entries()].map(([playerId,a])=>({playerId,nickname:r.participants.get(playerId)?.nickname||'Player',...a})));
broadcast(r);clearTimeout(r.revealTimer);if(r.mode==='death'&&activeParticipantCount(r)<=1)return finish(r);const nextQ=q.questions[r.questionIndex+1];const betweenDelay=3000;r.revealTimer=setTimeout(async()=>{if(r.mode==='death'&&activeParticipantCount(r)<=1){return finish(r)}if(r.questionIndex+1<q.questions.length){r.phase='between';io.to(r.code).emit('question:nextPreview',{index:r.questionIndex+1,total:q.questions.length,question:pubQ(q.questions[r.questionIndex+1])});broadcast(r);r.revealTimer=setTimeout(()=>startQuestion(r),betweenDelay)}else finish(r)},Math.max(0,+(qu.revealSeconds||5))*1000)}
function norm(v){return String(v??'').trim().toLowerCase().replace(/\s+/g,' ')}function correct(q,a){if(q.type==='multiple'){return JSON.stringify((Array.isArray(a)?a:[a]).map(norm).sort())===JSON.stringify((Array.isArray(q.answer)?q.answer:[q.answer]).map(norm).sort())}if(q.type==='ordering'){const aa=(Array.isArray(a)?a:[a]).map(Number);const qq=(Array.isArray(q.answer)?q.answer:[q.answer]).map(Number);return aa.length===qq.length&&aa.every((v,i)=>v===qq[i]);}if(q.type==='subjective')return (Array.isArray(q.answer)?q.answer:[q.answer]).map(norm).includes(norm(a));return norm(a)===norm(q.answer)}
async function syncPlayer(s,r){const q=await getQuiz(r.quizId);if(!q)return;
 if(r.mode==='speedrun'&&r.phase==='speedrun'){const p=r.participants.get(s.id);if(p?.speedFinished)s.emit('speedrun:goal',{score:p.score});else if(p)sendSpeedQuestion(r,p,q,false);return}
 if(r.phase==='riskChoice'&&r.questionIndex>=0){const left=Math.max(0,(r.riskDeadline||Date.now()+5000)-Date.now());s.emit('question:riskChoice',{index:r.questionIndex,total:q.questions.length,seconds:Math.ceil(left/1000),deadline:r.riskDeadline,question:pubQ(q.questions[r.questionIndex])});return}
 if(r.phase==='raidIntro'&&r.questionIndex>=0){const left=Math.max(0,(r.raidDeadline||Date.now()+3000)-Date.now());s.emit('question:raidIntro',{index:r.questionIndex,total:q.questions.length,seconds:Math.ceil(left/1000),deadline:r.raidDeadline,question:pubQ(q.questions[r.questionIndex])});return}
 if(r.phase==='question'&&r.questionIndex>=0){s.emit('question:start',{index:r.questionIndex,total:q.questions.length,question:pubQ(q.questions[r.questionIndex]),startedAt:r.startedAt});if(r.answers.has(s.id))s.emit('answer:locked',{ok:true,changed:false})}
 else if(r.phase==='reveal'&&r.questionIndex>=0){const qu=q.questions[r.questionIndex];const a=r.answers.get(s.id);s.emit('question:reveal',{index:r.questionIndex,correctAnswer:qu.answer,question:pubQ(qu),submitted:!!a,playerResult:a?{correct:!!a.correct,points:+(a.points||0),answer:a.answer}:null})}
 else if(r.phase==='between'&&r.questionIndex+1<q.questions.length){s.emit('question:nextPreview',{index:r.questionIndex+1,total:q.questions.length,question:pubQ(q.questions[r.questionIndex+1])})}
 else if(r.phase==='finished'){const results=r.finalResults||[...r.participants.values()].sort((a,b)=>b.score-a.score).map((p,i)=>({rank:i+1,playerId:p.playerId||null,nickname:p.nickname,avatar:p.avatar||'🦊',score:p.score,id:p.id,maxCombo:p.maxCombo||0,eliminated:!!p.eliminated,team:p.team||null}));s.emit('game:finished',{title:q.title,results,history:r.history,mode:r.mode||q.mode||'normal',comboEnabled:!!r.comboEnabled,noWinner:!!r.noWinner,matchId:r.matchId||null})}}
io.on('connection',s=>{s.on('host:join',async({code})=>{const r=rooms.get(String(code));if(!r)return s.emit('error:msg','방을 찾을 수 없습니다.');r.hostId=s.id;s.join(r.code);s.data.roomCode=r.code;s.data.host=true;const q=await getQuiz(r.quizId);s.emit('host:joined',snapshot(r,q));
if(r.phase==='speedrun'){s.emit('speedrun:start',{total:q.questions.length,title:q.title});const watch=[...r.participants.values()].find(x=>!x.disconnectedAt&&!x.eliminated&&!x.speedFinished);if(watch&&watch.speedIndex<q.questions.length)s.emit('speedrun:hostQuestion',{index:watch.speedIndex,total:q.questions.length,question:pubQ(q.questions[watch.speedIndex])});}
else if(r.phase==='riskChoice'&&r.questionIndex>=0){const left=Math.max(0,(r.riskDeadline||Date.now()+5000)-Date.now());s.emit('question:riskChoice',{index:r.questionIndex,total:q.questions.length,seconds:Math.ceil(left/1000),deadline:r.riskDeadline,question:pubQ(q.questions[r.questionIndex])});}
else if(r.phase==='raidIntro'&&r.questionIndex>=0){const left=Math.max(0,(r.raidDeadline||Date.now()+3000)-Date.now());s.emit('question:raidIntro',{index:r.questionIndex,total:q.questions.length,seconds:Math.ceil(left/1000),deadline:r.raidDeadline,question:pubQ(q.questions[r.questionIndex])});}
else if(r.phase==='question'&&r.questionIndex>=0)s.emit('question:start',{index:r.questionIndex,total:q.questions.length,question:pubQ(q.questions[r.questionIndex]),startedAt:r.startedAt});s.emit('host:answers',[...r.answers.entries()].map(([playerId,a])=>({playerId,nickname:r.participants.get(playerId)?.nickname||'Player',...a})));broadcast(r)});
s.on('player:join',async({code,nickname,reconnectToken,avatar,playerId})=>{
 const r=rooms.get(String(code));
 if(!r)return s.emit('error:msg','방을 찾을 수 없습니다.');
 let existing=null;
 if(reconnectToken)existing=[...r.participants.values()].find(p=>p.reconnectToken===reconnectToken);
 if(existing){
  const oldId=existing.id; existing.id=s.id; existing.disconnectedAt=null;
  r.participants.delete(oldId); r.participants.set(s.id,existing);
  if(r.answers.has(oldId)){const a=r.answers.get(oldId);r.answers.delete(oldId);r.answers.set(s.id,a)}
  s.data.reconnectToken=reconnectToken;s.data.roomCode=r.code;s.data.host=false;s.join(r.code);
  const rejoinedQuiz=await getQuiz(r.quizId);const reRaidQs=(rejoinedQuiz?.questions||[]).filter(x=>x.raidEnabled);const reRaidSummary=reRaidQs.length?reRaidQs.map((x,i)=>{const t=x.raidThresholdType==='percent'?`정답자 ${Math.max(1,Math.min(100,+x.raidThreshold||1))}%`:`정답자 ${Math.max(1,+x.raidThreshold||1)}명`;return `레이드 ${i+1}: ${t} 달성`}).join(' · '):'';s.emit('player:joined',{code:r.code,playerId:existing.playerId||null,nickname:existing.nickname,avatar:existing.avatar||'🦊',title:rejoinedQuiz?.title||'',reconnected:true,score:existing.score,reconnectToken,mode:r.mode||'normal',comboEnabled:!!r.comboEnabled,raidRules:{enabled:reRaidQs.length>0,summary:reRaidSummary}});
  broadcast(r);await syncPlayer(s,r);return;
 }
 if(r.participants.size>=32)return s.emit('error:msg','최대 32명까지 참가할 수 있습니다.');
 const token=id(24),allowedAvatars=['🦊','🐱','🐶','🐼','🐸','🐯','🐰','🐨','🦄','🐙','👾','🤖','sub1','sub2','sub3','sub4','sub5','sub6','sub7','sub8','sub9','sub10','sub11','sub12'];const safeAvatar=allowedAvatars.includes(String(avatar))?String(avatar):'🦊';const profile=await ensurePlayer(String(playerId||''));let assignedTeam=null;if(r.mode==='team'){const red=[...r.participants.values()].filter(p=>p.team==='red').length,blue=[...r.participants.values()].filter(p=>p.team==='blue').length;if(red<blue)assignedTeam='red';else if(blue<red)assignedTeam='blue';else assignedTeam=Math.random()<0.5?'red':'blue';}const p={id:s.id,playerId:profile.id,nickname:String(nickname||'Player').trim().slice(0,20)||'Player',avatar:safeAvatar,team:assignedTeam,score:0,combo:0,maxCombo:0,eliminated:false,reconnectToken:token,disconnectedAt:null};
 r.participants.set(s.id,p);if(r.mode==='speedrun'&&r.phase==='speedrun'){p.speedIndex=0;p.speedRunStartedAt=Date.now();p.speedStartedAt=p.speedRunStartedAt;p.speedHistory=[];p.speedFinished=false} s.join(r.code);s.data.roomCode=r.code;s.data.reconnectToken=token;
 const joinedQuiz=await getQuiz(r.quizId);const raidQs=(joinedQuiz?.questions||[]).filter(x=>x.raidEnabled);const raidSummary=raidQs.length?raidQs.map((x,i)=>{const t=x.raidThresholdType==='percent'?`정답자 ${Math.max(1,Math.min(100,+x.raidThreshold||1))}%`:`정답자 ${Math.max(1,+x.raidThreshold||1)}명`;return `레이드 ${i+1}: ${t} 달성`}).join(' · '):'';s.emit('player:joined',{code:r.code,playerId:p.playerId,nickname:p.nickname,avatar:p.avatar,title:joinedQuiz?.title||'',reconnectToken:token,mode:r.mode||'normal',comboEnabled:!!r.comboEnabled,raidRules:{enabled:raidQs.length>0,summary:raidSummary}});
 broadcast(r);await syncPlayer(s,r);
});
s.on('host:start',()=>{const r=rooms.get(s.data.roomCode);if(!r||!s.data.host||r.phase!=='lobby'||r.starting)return;if(r.mode==='team'){const n=activeParticipantCount(r);if(n<2)return s.emit('error:msg','팀 모드는 2명 이상이 필요합니다.');}r.starting=true;void startQuestion(r).catch(e=>{r.starting=false;console.error('START ERROR',e);s.emit('error:msg','게임 시작 중 오류가 발생했습니다.')})});
s.on('host:skip',async()=>{const r=rooms.get(s.data.roomCode);if(!r||!s.data.host)return;if(r.phase==='question'){clearTimeout(r.nextTimer);await reveal(r)}else if(r.phase==='reveal'||r.phase==='between'){clearTimeout(r.revealTimer);const q=await getQuiz(r.quizId);if(r.questionIndex+1<q.questions.length){r.phase='between';io.to(r.code).emit('question:nextPreview',{index:r.questionIndex+1,total:q.questions.length,question:pubQ(q.questions[r.questionIndex+1])});broadcast(r);r.revealTimer=setTimeout(()=>startQuestion(r),50)}else finish(r)}});
s.on('player:answer',async({answer},ack)=>{const reply=(v)=>{if(typeof ack==='function')ack(v)};const r=rooms.get(s.data.roomCode);if(!r||!r.participants.has(s.id))return reply({ok:false,error:'문제가 이미 종료되었습니다.'});
const player=r.participants.get(s.id);if(player?.eliminated)return reply({ok:false,error:'데스 모드에서 탈락했습니다.'});if(r.mode==='speedrun')return handleSpeedAnswer(r,s,answer,reply);if(r.phase!=='question')return reply({ok:false,error:'지금은 답안을 제출할 수 없습니다.'});const q=(await getQuiz(r.quizId)).questions[r.questionIndex];const old=r.answers.get(s.id);if(old&&!q.allowAnswerChange)return reply({ok:false,error:'이미 제출한 답안입니다.'});const elapsed=Date.now()-r.startedAt,limit=Math.max(1,+(q.timeLimit||15))*1000;if(elapsed>=limit)return reply({ok:false,error:'제출 시간이 종료되었습니다.'});const is=correct(q,answer);let points=0;if(is){const ratio=Math.max(0,1-Math.min(elapsed,limit)/limit);points=Math.round((500+500*ratio)*(q.platinum?3:q.fever?2:1));if(r.mode!=='death'&&q.highRisk&&player.riskChoice==='challenge')points*=2}else if(r.mode!=='death'&&q.highRisk&&player.riskChoice==='challenge'){points=-Math.round((500+500*Math.max(0,1-Math.min(elapsed,limit)/limit))*(q.platinum?3:q.fever?2:1))}r.answers.set(s.id,{answer,correct:is,points,basePoints:points,elapsed,scoreCommitted:false});reply({ok:true,changed:!!old});s.emit('answer:locked',{ok:true,changed:!!old});if(r.hostId)io.to(r.hostId).emit('host:answers',[...r.answers.entries()].map(([playerId,a])=>({playerId,nickname:r.participants.get(playerId)?.nickname||'Player',...a})));broadcast(r);maybeReveal(r,q)});
async function handleSpeedAnswer(r,s,answer,reply){const q=await getQuiz(r.quizId);const p=r.participants.get(s.id);if(!q||!p||r.phase!=='speedrun'||p.speedFinished)return reply({ok:false,error:'이미 완료했거나 게임이 종료되었습니다.'});const qu=q.questions[p.speedIndex];const elapsed=Date.now()-p.speedStartedAt;if(elapsed>=Math.max(1,+(qu.timeLimit||15))*1000)return reply({ok:false,error:'제출 시간이 종료되었습니다.'});const is=correct(qu,answer);const limit=Math.max(1,+(qu.timeLimit||15))*1000;let points=is?speedPoints(elapsed,limit,qu):0;const row={index:p.speedIndex,correct:is,elapsed,points};p.score+=points;p.speedHistory.push(row);reply({ok:true,correct:is,points,elapsed});io.to(p.id).emit('speedrun:result',{index:p.speedIndex,correct:is,points,elapsed,nextIndex:p.speedIndex+1});p.speedIndex++;sendSpeedQuestion(r,p,q);broadcast(r)}
s.on('speedrun:timeout',async({index})=>{const r=rooms.get(s.data.roomCode);if(!r||r.phase!=='speedrun')return;const p=r.participants.get(s.id);if(!p||p.speedFinished||p.speedIndex!==Number(index))return;const q=await getQuiz(r.quizId);const qu=q?.questions?.[p.speedIndex];if(!qu)return;p.speedHistory.push({index:p.speedIndex,correct:false,elapsed:Math.max(1,+(qu.timeLimit||15))*1000,points:0});p.speedIndex++;sendSpeedQuestion(r,p,q);broadcast(r)});s.on('question:riskChoice',({choice})=>{const r=rooms.get(s.data.roomCode);if(!r||r.phase!=='riskChoice'||!r.participants.has(s.id))return;const p=r.participants.get(s.id);p.riskChoice=choice==='challenge'?'challenge':'coward';s.emit('question:riskChoiceAck',{choice:p.riskChoice});broadcast(r)});
s.on('question:timeoutCheck',async({index})=>{try{const r=rooms.get(s.data.roomCode);if(!r||r.phase!=='question'||r.questionIndex!==Number(index))return;const q=(await getQuiz(r.quizId))?.questions?.[r.questionIndex];if(!q)return;const limit=Math.max(1,+(q.timeLimit||15))*1000;if(Date.now()-r.startedAt>=limit){clearTimeout(r.nextTimer);await reveal(r)}}catch(e){console.error('TIMEOUT WATCHDOG ERROR',e)}});
s.on('disconnect',()=>{const r=rooms.get(s.data.roomCode);if(!r)return;if(r.hostId===s.id){io.to(r.code).emit('error:msg','주최자가 나가서 방이 종료되었습니다.');rooms.delete(r.code);return}const p=r.participants.get(s.id);if(p){p.disconnectedAt=Date.now();setTimeout(()=>{const cur=r.participants.get(s.id);if(cur&&cur.disconnectedAt&&Date.now()-cur.disconnectedAt>=60000){r.participants.delete(s.id);r.answers.delete(s.id);broadcast(r)}},60000)}broadcast(r)})});
app.use((req,res)=>res.sendFile(require('path').join(__dirname,'public','index.html')));
init().then(()=>server.listen(PORT,'0.0.0.0',()=>console.log('QUIZ LIVE ONLINE on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
