const express=require('express');const http=require('http');const crypto=require('crypto');const path=require('path');const {Server}=require('socket.io');const {Pool}=require('pg');const multer=require('multer');const QRCode=require('qrcode');
const app=express(),server=http.createServer(app),io=new Server(server,{maxHttpBufferSize:2*1024*1024});const PORT=process.env.PORT||3000;
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false}}):null;
const fs=require('fs');const localFile=path.join(__dirname,'data','quizzes.json');const uploadDir=path.join(__dirname,'uploads');fs.mkdirSync(path.dirname(localFile),{recursive:true});fs.mkdirSync(uploadDir,{recursive:true});if(!fs.existsSync(localFile))fs.writeFileSync(localFile,'{}');
const rooms=new Map();const id=n=>crypto.randomBytes(Math.ceil(n/2)).toString('hex').slice(0,n);
async function init(){if(pool){await pool.query(`CREATE TABLE IF NOT EXISTS quizzes(id TEXT PRIMARY KEY,title TEXT NOT NULL,theme JSONB NOT NULL DEFAULT '{}',questions JSONB NOT NULL,owner_token TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now())`)} }
async function getQuiz(qid){let q;if(pool){const r=await pool.query('SELECT id,title,theme,questions,owner_token AS "ownerToken",created_at AS "createdAt",updated_at AS "updatedAt" FROM quizzes WHERE id=$1',[qid]);q=r.rows[0]||null}else{const d=JSON.parse(fs.readFileSync(localFile));q=d[qid]||null}if(q){q=await migrateLegacyAudio(q);q=await migrateLegacyImages(q)}return q}
async function saveQuiz(q){if(pool){await pool.query(`INSERT INTO quizzes(id,title,theme,questions,owner_token) VALUES($1,$2,$3,$4,$5) ON CONFLICT(id) DO UPDATE SET title=$2,theme=$3,questions=$4,updated_at=now()`,[q.id,q.title,JSON.stringify(q.theme||{}),JSON.stringify(q.questions||[]),q.ownerToken])}else{const d=JSON.parse(fs.readFileSync(localFile));d[q.id]=q;fs.writeFileSync(localFile,JSON.stringify(d,null,2))}}
async function deleteQuiz(qid){if(pool)await pool.query('DELETE FROM quizzes WHERE id=$1',[qid]);else{const d=JSON.parse(fs.readFileSync(localFile));delete d[qid];fs.writeFileSync(localFile,JSON.stringify(d,null,2))}}
const MAX_AUDIO_BYTES=20*1024*1024;const MAX_IMAGE_BYTES=5*1024*1024;
function dataUrlBytes(v){if(typeof v!=='string'||!v.startsWith('data:'))return 0;const i=v.indexOf(',');if(i<0)return 0;const meta=v.slice(5,i);const body=v.slice(i+1);if(/;base64/i.test(meta))return Math.floor(body.length*3/4)-((body.endsWith('==')?2:body.endsWith('=')?1:0));return new TextEncoder().encode(decodeURIComponent(body)).length}
function validateQuizMedia(questions){for(const q of questions||[]){if(q.audioUrl&&String(q.audioUrl).startsWith('data:')){const bytes=dataUrlBytes(q.audioUrl);if(bytes>MAX_AUDIO_BYTES)return '음악 파일은 문제당 최대 20MB까지 사용할 수 있습니다.';if(!/^data:audio\//i.test(q.audioUrl))return '음악 파일 형식이 올바르지 않습니다.';}}return null}

function safeAudioExt(originalName,mime){const ext=path.extname(originalName||'').toLowerCase();const allowed={'.mp3':'audio/mpeg','.wav':'audio/wav','.m4a':'audio/mp4','.ogg':'audio/ogg','.oga':'audio/ogg','.webm':'audio/webm','.aac':'audio/aac','.flac':'audio/flac'};return allowed[ext]===mime?ext:(mime==='audio/mpeg'?'.mp3':mime==='audio/wav'?'.wav':mime==='audio/mp4'?'.m4a':mime==='audio/ogg'?'.ogg':mime==='audio/webm'?'.webm':'.bin')}
function writeDataUrlAudio(dataUrl,name){if(typeof dataUrl!=='string'||!/^data:audio\//i.test(dataUrl))return null;const comma=dataUrl.indexOf(',');if(comma<0)return null;const meta=dataUrl.slice(5,comma),body=dataUrl.slice(comma+1);const mime=(meta.split(';')[0]||'audio/mpeg').toLowerCase();const buf=/;base64/i.test(meta)?Buffer.from(body,'base64'):Buffer.from(decodeURIComponent(body),'utf8');if(buf.length>MAX_AUDIO_BYTES)throw Object.assign(new Error('audio too large'),{code:'LIMIT_FILE_SIZE'});const filename=id(24)+safeAudioExt(name,mime);fs.writeFileSync(path.join(uploadDir,filename),buf);return '/uploads/'+filename}
async function migrateLegacyAudio(q){let changed=false;for(const item of q.questions||[]){if(item.audioUrl&&String(item.audioUrl).startsWith('data:audio/')){const url=writeDataUrlAudio(item.audioUrl,item.audioName||'audio.mp3');if(url){item.audioUrl=url;changed=true}}}if(changed)await saveQuiz(q);return q}

function safeImageExt(originalName,mime){const ext=path.extname(originalName||'').toLowerCase();const allowed={'.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp','.gif':'image/gif'};return allowed[ext]===mime?ext:(mime==='image/png'?'.png':mime==='image/webp'?'.webp':mime==='image/gif'?'.gif':'.jpg')}
const imageStorage=multer.diskStorage({destination:(req,file,cb)=>cb(null,uploadDir),filename:(req,file,cb)=>cb(null,id(24)+safeImageExt(file.originalname,file.mimetype))});
const uploadImage=multer({storage:imageStorage,limits:{fileSize:MAX_IMAGE_BYTES},fileFilter:(req,file,cb)=>cb(null,/^image\/(jpeg|png|webp|gif)$/i.test(file.mimetype))});
function writeDataUrlImage(dataUrl,name){if(typeof dataUrl!=='string'||!/^data:image\//i.test(dataUrl))return null;const comma=dataUrl.indexOf(',');if(comma<0)return null;const meta=dataUrl.slice(5,comma),body=dataUrl.slice(comma+1),mime=(meta.split(';')[0]||'image/jpeg').toLowerCase();const buf=/;base64/i.test(meta)?Buffer.from(body,'base64'):Buffer.from(decodeURIComponent(body),'utf8');if(buf.length>MAX_IMAGE_BYTES)throw Object.assign(new Error('image too large'),{code:'LIMIT_FILE_SIZE'});const filename=id(24)+safeImageExt(name,mime);fs.writeFileSync(path.join(uploadDir,filename),buf);return '/uploads/'+filename}
async function migrateLegacyImages(q){let changed=false;for(const item of q.questions||[]){if(item.imageUrl&&String(item.imageUrl).startsWith('data:image/')){const url=writeDataUrlImage(item.imageUrl,item.imageName||'image.jpg');if(url){item.imageUrl=url;item.imageName=item.imageName||'legacy image';changed=true}}}if(q.theme&&q.theme.background&&String(q.theme.background).startsWith('data:image/')){const url=writeDataUrlImage(q.theme.background,'background.jpg');if(url){q.theme.background=url;changed=true}}if(changed)await saveQuiz(q);return q}

const audioStorage=multer.diskStorage({destination:(req,file,cb)=>cb(null,uploadDir),filename:(req,file,cb)=>cb(null,id(24)+safeAudioExt(file.originalname,file.mimetype))});
const uploadAudio=multer({storage:audioStorage,limits:{fileSize:MAX_AUDIO_BYTES},fileFilter:(req,file,cb)=>cb(null,/^audio\//i.test(file.mimetype))});
app.use(express.json({limit:'120mb'}));
app.use((err,req,res,next)=>{if(err&&err.type==='entity.too.large')return res.status(413).json({error:'퀴즈 저장 데이터가 너무 큽니다. 음악 파일은 문제당 20MB 이하로 사용하고, 전체 퀴즈 크기를 줄여주세요.'});if(err)return res.status(400).json({error:'퀴즈 데이터 형식이 올바르지 않습니다.'});next(err)});
app.use(express.static(path.join(__dirname,'public')));app.use('/uploads',express.static(uploadDir));
app.post('/api/upload-audio',uploadAudio.single('audio'),(req,res)=>{if(!req.file)return res.status(400).json({error:'음악 파일을 선택해주세요.'});res.json({ok:true,url:'/uploads/'+req.file.filename,name:req.file.originalname,size:req.file.size,mime:req.file.mimetype})});
app.post('/api/upload-image',uploadImage.single('image'),(req,res)=>{if(!req.file)return res.status(400).json({error:'이미지 파일을 선택해주세요.'});res.json({ok:true,url:'/uploads/'+req.file.filename,name:req.file.originalname,size:req.file.size,mime:req.file.mimetype})});
app.get('/api/room/:code/qr',async(req,res)=>{try{const r=rooms.get(String(req.params.code));if(!r)return res.status(404).send('Not found');const proto=req.get('x-forwarded-proto')||req.protocol;const joinUrl=`${proto}://${req.get('host')}/?room=${encodeURIComponent(r.code)}`;res.type('svg').send(await QRCode.toString(joinUrl,{type:'svg',margin:1,width:280,color:{dark:'#111827',light:'#ffffff'}}))}catch(e){res.status(500).send('QR error')}});
app.use((err,req,res,next)=>{if(err instanceof multer.MulterError&&err.code==='LIMIT_FILE_SIZE')return res.status(413).json({error:'음악 파일은 최대 20MB까지 업로드할 수 있습니다.'});if(err&&err.message==='Unexpected field')return res.status(400).json({error:'음악 업로드 요청이 올바르지 않습니다.'});if(err)return res.status(400).json({error:'파일 업로드에 실패했습니다.'});next(err)});
app.get('/api/quiz/:id',async(req,res)=>{const q=await getQuiz(req.params.id);if(!q)return res.status(404).json({error:'Quiz not found'});const {ownerToken,...pub}=q;res.json(pub)});
app.get('/api/manage/:id/:token',async(req,res)=>{const q=await getQuiz(req.params.id);if(!q)return res.status(404).json({error:'Quiz not found'});if(req.params.token!==q.ownerToken)return res.status(403).json({error:'관리 링크가 올바르지 않습니다.'});const {ownerToken,...pub}=q;res.json(pub)});
app.post('/api/quizzes',async(req,res)=>{try{const b=req.body||{};if(!b.title||!Array.isArray(b.questions)||!b.questions.length)return res.status(400).json({error:'Title and questions are required.'});const mediaError=validateQuizMedia(b.questions);if(mediaError)return res.status(413).json({error:mediaError});const q={id:id(10),title:String(b.title).slice(0,120),theme:b.theme||{},questions:b.questions,ownerToken:id(32)};await saveQuiz(q);res.json({id:q.id,ownerToken:q.ownerToken})}catch(e){console.error('CREATE QUIZ ERROR',e);res.status(500).json({error:'퀴즈 저장 중 서버 오류가 발생했습니다.'})}});
app.put('/api/quizzes/:id',async(req,res)=>{try{const q=await getQuiz(req.params.id);if(!q)return res.status(404).json({error:'Quiz not found'});if(req.headers['x-owner-token']!==q.ownerToken)return res.status(403).json({error:'Only the creator can edit this quiz.'});q.title=String(req.body.title||q.title).slice(0,120);q.theme=req.body.theme||q.theme;q.questions=Array.isArray(req.body.questions)?req.body.questions:q.questions;const mediaError=validateQuizMedia(q.questions);if(mediaError)return res.status(413).json({error:mediaError});await saveQuiz(q);res.json({ok:true})}catch(e){console.error('UPDATE QUIZ ERROR',e);res.status(500).json({error:'퀴즈 수정 저장 중 서버 오류가 발생했습니다.'})}});
app.delete('/api/quizzes/:id',async(req,res)=>{const q=await getQuiz(req.params.id);if(!q)return res.status(404).json({error:'Quiz not found'});if(req.headers['x-owner-token']!==q.ownerToken)return res.status(403).json({error:'Only the creator can delete this quiz.'});await deleteQuiz(q.id);res.json({ok:true})});
app.post('/api/rooms',async(req,res)=>{const q=await getQuiz(req.body.quizId);if(!q)return res.status(404).json({error:'Quiz not found'});let code;do code=String(Math.floor(100000+Math.random()*900000));while(rooms.has(code));rooms.set(code,{code,quizId:q.id,hostId:null,phase:'lobby',questionIndex:-1,startedAt:null,participants:new Map(),answers:new Map(),history:[],nextTimer:null,revealTimer:null,riskTimer:null,mode:q.mode||'normal',comboEnabled:q.comboEnabled!==false&&!!q.comboEnabled});res.json({code})});
function pubQ(q){return {type:q.type,prompt:q.prompt,options:q.type==='ox'?['O','X']:(q.options||[]),mode:q.mode||'normal',comboEnabled:!!q.comboEnabled,imageUrl:q.imageUrl||'',videoId:q.videoId||'',audioUrl:q.audioUrl||'',audioName:q.audioName||'',start:+(q.start||0),end:+(q.end||0),showVideo:q.showVideo!==false,colors:Array.isArray(q.colors)?q.colors:[],timeLimit:Math.max(1,+(q.timeLimit||15)),revealEnabled:q.revealEnabled!==false,revealSeconds:Math.max(0,+(q.revealSeconds||5)),fever:!!q.fever,platinum:!!q.platinum,allowAnswerChange:!!q.allowAnswerChange,waitFullTime:q.waitFullTime!==false}};
function teamStats(r){const out={red:{correct:0,total:0},blue:{correct:0,total:0}};for(const h of r.history||[]){for(const x of h.players||[]){const p=[...r.participants.values()].find(z=>z.reconnectToken===x.key);if(!p||!p.team||!x.submitted)continue;out[p.team].total++;if(x.correct)out[p.team].correct++}}return out}function snapshot(r,q){const qu=r.questionIndex>=0?q.questions[r.questionIndex]:null;const answerCounts=(qu&&Array.isArray(qu.options))?qu.options.map((o,i)=>[...r.answers.values()].reduce((n,a)=>{const vals=Array.isArray(a.answer)?a.answer:[a.answer];return n+(vals.some(v=>norm(v)===norm(o))?1:0)},0)):[];const ts=teamStats(r);return {code:r.code,title:q.title,theme:q.theme||{},phase:r.phase,questionIndex:r.questionIndex,totalQuestions:q.questions.length,answerCounts,answeredCount:r.answers.size,participants:[...r.participants.values()].map(p=>({id:p.id,nickname:p.nickname,avatar:p.avatar||'🦊',score:p.score,combo:p.combo||0,maxCombo:p.maxCombo||0,eliminated:!!p.eliminated,answered:r.answers.has(p.id),team:p.team||null,teamAccuracy:p.team? (ts[p.team].total?Math.round(ts[p.team].correct/ts[p.team].total*100):0):null,speedIndex:p.speedIndex||0,speedFinished:!!p.speedFinished,speedElapsed:p.speedStartedAt?Date.now()-p.speedStartedAt:0})),mode:r.mode||q.mode||'normal',comboEnabled:!!r.comboEnabled}};
async function broadcast(r){const q=await getQuiz(r.quizId);if(q)io.to(r.code).emit('room:state',snapshot(r,q))}
function activeParticipantCount(r){return [...r.participants.values()].filter(p=>!p.disconnectedAt&&p.id&&!p.eliminated).length}
function raidConfig(q,r){return r.mode!=='team'&&r.mode!=='speedrun'&&q&&q.raidEnabled&&q.type==='choice'&&Array.isArray(q.options)&&q.options.length===8}function raidThreshold(r,q){const n=[...r.participants.values()].filter(p=>!p.disconnectedAt&&!p.eliminated).length;if((q.raidThresholdType||'count')==='percent')return Math.max(1,Math.ceil(n*Math.max(1,Math.min(100,+q.raidThreshold||1))/100));return Math.max(1,Math.min(n,+q.raidThreshold||1))}function speedPoints(elapsed,limit,q){const ratio=Math.max(0,1-Math.min(elapsed,limit)/limit);const tier=ratio>=.75?1000:ratio>=.5?750:ratio>=.25?500:250;return Math.round(tier*(q.platinum?3:q.fever?2:1))}function startRiskChoice(r){getQuiz(r.quizId).then(q=>{if(!q||r.phase==='finished')return;const qu=q.questions[r.questionIndex];if(!qu||!qu.highRisk){beginQuestion(r);return}r.phase='riskChoice';for(const p of r.participants.values()){p.riskChoice='coward'}io.to(r.code).emit('question:riskChoice',{index:r.questionIndex,total:q.questions.length,seconds:5,question:pubQ(qu)});broadcast(r);clearTimeout(r.riskTimer);r.riskTimer=setTimeout(()=>beginQuestion(r),5000)})}async function beginQuestion(r){const q=await getQuiz(r.quizId);if(!q||r.phase==='finished')return;const qu=q.questions[r.questionIndex];r.phase='question';r.answers=new Map();r.startedAt=Date.now();for(const p of r.participants.values())if(!p.eliminated)p.riskChoice=p.riskChoice||'coward';io.to(r.code).emit('question:start',{index:r.questionIndex,total:q.questions.length,question:pubQ(qu)});broadcast(r);clearTimeout(r.nextTimer);const idx=r.questionIndex;const delay=Math.max(1,+(qu.timeLimit||15))*1000;r.nextTimer=setTimeout(()=>{if(r.phase==='question'&&r.questionIndex===idx)void reveal(r).catch(e=>console.error('REVEAL TIMER ERROR',e))},delay)}function startSpeedrun(r){getQuiz(r.quizId).then(q=>{r.phase='speedrun';r.startedAt=Date.now();for(const p of r.participants.values()){p.speedIndex=0;p.speedStartedAt=Date.now();p.speedHistory=[];p.speedFinished=false}for(const p of r.participants.values())sendSpeedQuestion(r,p,q)});}
async function sendSpeedQuestion(r,p,q,resetClock=true){if(!p||p.eliminated||p.speedFinished)return;if(p.speedIndex>=q.questions.length){p.speedFinished=true;p.speedGoalAt=Date.now();io.to(p.id).emit('speedrun:goal',{score:p.score});if([...r.participants.values()].filter(x=>!x.disconnectedAt&&!x.eliminated).every(x=>x.speedFinished))return finishSpeedrun(r);broadcast(r);return}const qu=q.questions[p.speedIndex];if(resetClock||!p.speedStartedAt)p.speedStartedAt=Date.now();io.to(p.id).emit('speedrun:question',{index:p.speedIndex,total:q.questions.length,question:pubQ(qu),score:p.score});broadcast(r)}async function finishSpeedrun(r){const q=await getQuiz(r.quizId);r.phase='finished';const results=[...r.participants.values()].sort((a,b)=>b.score-a.score).map((p,i)=>({rank:i+1,nickname:p.nickname,avatar:p.avatar||'🦊',score:p.score,id:p.id,correctCount:(p.speedHistory||[]).filter(x=>x.correct).length,answered:(p.speedHistory||[]).length,totalQuestions:q.questions.length,accuracy:p.speedHistory?.length?Math.round(p.speedHistory.filter(x=>x.correct).length/p.speedHistory.length*100):0,avgResponseMs:p.speedHistory?.length?Math.round(p.speedHistory.reduce((a,x)=>a+x.elapsed,0)/p.speedHistory.length):0,maxCombo:0,eliminated:false}));io.to(r.code).emit('game:finished',{title:q.title,results,history:r.history||[],mode:'speedrun',comboEnabled:false});broadcast(r)}
function maybeReveal(r,q){if(!q||(r.mode!=='speedrun'&&q.waitFullTime!==false)||r.phase!=='question')return false;const active=activeParticipantCount(r);if(active>0&&r.answers.size>=active){clearTimeout(r.nextTimer);void reveal(r);return true}return false}
async function finish(r){const q=await getQuiz(r.quizId);r.phase='finished';const results=[...r.participants.values()].sort((a,b)=>(r.mode==='survival'?Number(a.eliminated)-Number(b.eliminated):0)||b.score-a.score).map((p,i)=>{const rows=r.history.map(h=>h.players.find(x=>x.key===p.reconnectToken)).filter(Boolean);const answered=rows.filter(x=>x.submitted).length,correctCount=rows.filter(x=>x.correct).length,elapsed=rows.filter(x=>x.submitted).map(x=>x.elapsed);return {rank:i+1,nickname:p.nickname,avatar:p.avatar||'🦊',score:p.score,id:p.id,correctCount,answered,totalQuestions:q.questions.length,accuracy:answered?Math.round(correctCount/answered*100):0,avgResponseMs:elapsed.length?Math.round(elapsed.reduce((a,b)=>a+b,0)/elapsed.length):0,maxCombo:p.maxCombo||0,eliminated:!!p.eliminated}});io.to(r.code).emit('game:finished',{title:q.title,results,history:r.history,mode:r.mode||q.mode||'normal',comboEnabled:!!r.comboEnabled}) ;broadcast(r)}
async function reveal(r){const q=await getQuiz(r.quizId);if(!q||r.phase!=='question')return;const qu=q.questions[r.questionIndex];const idx=r.questionIndex;
const raid=raidConfig(qu,r);let raidSuccess=false;let raidCorrectCount=0;if(raid){raidCorrectCount=[...r.answers.values()].filter(a=>a.correct).length;raidSuccess=raidCorrectCount>=raidThreshold(r,qu);}
// Score is intentionally committed only at reveal time. v6.5.1 audit: points are not added during submission. During the question,
// participants see their previous total so a correct answer is never spoiled early.
for(const p of r.participants.values()){const a=r.answers.get(p.id);if(p.eliminated)continue;if(a&&!a.scoreCommitted){if(raid&&!raidSuccess){a.points=a.correct?0:-(a.basePoints||0);a.combo=0}else if(raid&&raidSuccess){if(a.correct)a.points=a.basePoints||0;else a.points=0}else if(a.correct&&r.comboEnabled){p.combo=(p.combo||0)+1;p.maxCombo=Math.max(p.maxCombo||0,p.combo);a.combo=p.combo;a.comboBonus=Math.max(0,(p.combo-1)*100);a.points=(a.basePoints||a.points||0)+a.comboBonus}else if(a){if(!a.correct&&r.comboEnabled)p.combo=0;a.combo=p.combo||0;a.comboBonus=0;a.points=a.basePoints||a.points||0}if(a)p.score+=a.points||0;a.scoreCommitted=true}}
if(r.mode==='survival'){for(const p of r.participants.values()){if(p.eliminated)continue;const a=r.answers.get(p.id);if(!a||!a.correct)p.eliminated=true;if(!a||!a.correct)p.combo=0}}
r.history.push({index:idx,correctAnswer:qu.answer,players:[...r.participants.values()].map(p=>{const a=r.answers.get(p.id);return {key:p.reconnectToken,submitted:!!a,correct:!!a?.correct,elapsed:a?.elapsed||0,points:a?.points||0,basePoints:a?.basePoints||a?.points||0,combo:a?.combo||0,comboBonus:a?.comboBonus||0,eliminated:!!p.eliminated}})});
r.phase='reveal';
// The reveal packet itself contains each player's authoritative result.
for(const p of r.participants.values()){
  const a=r.answers.get(p.id);
  io.to(p.id).emit('question:reveal',{index:idx,correctAnswer:qu.answer,question:pubQ(qu),submitted:!!a,playerResult:a?{correct:!!a.correct,points:+(a.points||0),answer:a.answer}:null,raid:raid?{enabled:true,success:raidSuccess,threshold:raidThreshold(r,qu),correctCount:raidCorrectCount,leaders:raidSuccess?[...r.answers.entries()].filter(([,a])=>a.correct).sort((x,y)=>(x[1].elapsed||0)-(y[1].elapsed||0)).slice(0,raidThreshold(r,qu)).map(([pid,a])=>({nickname:r.participants.get(pid)?.nickname||'Player',avatar:r.participants.get(pid)?.avatar||'🦊',points:+(a.points||0)})):[]}:null});
}
if(r.hostId)io.to(r.hostId).emit('host:answers',[...r.answers.entries()].map(([playerId,a])=>({playerId,nickname:r.participants.get(playerId)?.nickname||'Player',...a})));
broadcast(r);clearTimeout(r.revealTimer);r.revealTimer=setTimeout(async()=>{if(r.mode==='survival'&&activeParticipantCount(r)<=1){return finish(r)}if(r.questionIndex+1<q.questions.length){r.phase='between';io.to(r.code).emit('question:nextPreview',{index:r.questionIndex+1,total:q.questions.length,question:pubQ(q.questions[r.questionIndex+1])});broadcast(r);r.revealTimer=setTimeout(()=>startQuestion(r),3000)}else finish(r)},Math.max(0,+(qu.revealSeconds||5))*1000)}
async function startQuestion(r){const q=await getQuiz(r.quizId);if(r.mode==='speedrun')return startSpeedrun(r);r.questionIndex++;if(r.questionIndex>=q.questions.length)return finish(r);const qu=q.questions[r.questionIndex];if(qu.highRisk)return startRiskChoice(r);return beginQuestion(r)}
function norm(v){return String(v??'').trim().toLowerCase().replace(/\s+/g,' ')}function correct(q,a){if(q.type==='multiple'){return JSON.stringify((Array.isArray(a)?a:[a]).map(norm).sort())===JSON.stringify((Array.isArray(q.answer)?q.answer:[q.answer]).map(norm).sort())}if(q.type==='ordering'){const aa=(Array.isArray(a)?a:[a]).map(Number);const qq=(Array.isArray(q.answer)?q.answer:[q.answer]).map(Number);return aa.length===qq.length&&aa.every((v,i)=>v===qq[i]);}if(q.type==='subjective')return (Array.isArray(q.answer)?q.answer:[q.answer]).map(norm).includes(norm(a));return norm(a)===norm(q.answer)}
async function syncPlayer(s,r){const q=await getQuiz(r.quizId);if(!q)return;if(r.mode==='speedrun'&&r.phase==='speedrun'){const p=r.participants.get(s.id);if(p?.speedFinished)s.emit('speedrun:goal',{score:p.score});else if(p)sendSpeedQuestion(r,p,q,false);return}if(r.phase==='riskChoice'&&r.questionIndex>=0){s.emit('question:riskChoice',{index:r.questionIndex,total:q.questions.length,seconds:5,question:pubQ(q.questions[r.questionIndex])});return}if(r.phase==='question'&&r.questionIndex>=0){s.emit('question:start',{index:r.questionIndex,total:q.questions.length,question:pubQ(q.questions[r.questionIndex]),startedAt:r.startedAt});if(r.answers.has(s.id))s.emit('answer:locked',{ok:true,changed:false})}else if(r.phase==='reveal'&&r.questionIndex>=0){const qu=q.questions[r.questionIndex];const a=r.answers.get(s.id);s.emit('question:reveal',{index:r.questionIndex,correctAnswer:qu.answer,question:pubQ(qu),submitted:!!a,playerResult:a?{correct:!!a.correct,points:+(a.points||0),answer:a.answer}:null})}else if(r.phase==='between'&&r.questionIndex+1<q.questions.length){s.emit('question:nextPreview',{index:r.questionIndex+1,total:q.questions.length,question:pubQ(q.questions[r.questionIndex+1])})}else if(r.phase==='finished'){const results=[...r.participants.values()].sort((a,b)=>(r.mode==='survival'?Number(a.eliminated)-Number(b.eliminated):0)||b.score-a.score).map((p,i)=>({rank:i+1,nickname:p.nickname,avatar:p.avatar||'🦊',score:p.score,id:p.id,maxCombo:p.maxCombo||0,eliminated:!!p.eliminated}));s.emit('game:finished',{title:q.title,results,history:r.history,mode:r.mode||q.mode||'normal',comboEnabled:!!r.comboEnabled})}}
io.on('connection',s=>{s.on('host:join',async({code})=>{const r=rooms.get(String(code));if(!r)return s.emit('error:msg','방을 찾을 수 없습니다.');r.hostId=s.id;s.join(r.code);s.data.roomCode=r.code;s.data.host=true;const q=await getQuiz(r.quizId);s.emit('host:joined',snapshot(r,q));if(r.phase==='question'&&r.questionIndex>=0)s.emit('question:start',{index:r.questionIndex,total:q.questions.length,question:pubQ(q.questions[r.questionIndex]),startedAt:r.startedAt});s.emit('host:answers',[...r.answers.entries()].map(([playerId,a])=>({playerId,nickname:r.participants.get(playerId)?.nickname||'Player',...a})));broadcast(r)});
s.on('player:join',async({code,nickname,reconnectToken,avatar})=>{
 const r=rooms.get(String(code));
 if(!r)return s.emit('error:msg','방을 찾을 수 없습니다.');
 let existing=null;
 if(reconnectToken)existing=[...r.participants.values()].find(p=>p.reconnectToken===reconnectToken);
 if(existing){
  const oldId=existing.id; existing.id=s.id; existing.disconnectedAt=null;
  r.participants.delete(oldId); r.participants.set(s.id,existing);
  if(r.answers.has(oldId)){const a=r.answers.get(oldId);r.answers.delete(oldId);r.answers.set(s.id,a)}
  s.data.reconnectToken=reconnectToken;s.data.roomCode=r.code;s.data.host=false;s.join(r.code);
  s.emit('player:joined',{code:r.code,nickname:existing.nickname,avatar:existing.avatar||'🦊',title:(await getQuiz(r.quizId)).title,reconnected:true,score:existing.score,reconnectToken});
  broadcast(r);await syncPlayer(s,r);return;
 }
 if(r.participants.size>=32)return s.emit('error:msg','최대 32명까지 참가할 수 있습니다.');
 const token=id(24),allowedAvatars=['🦊','🐱','🐶','🐼','🐸','🐯','🐰','🐨','🦄','🐙','👾','🤖','sub1','sub2','sub3','sub4','sub5','sub6','sub7','sub8','sub9','sub10','sub11','sub12'];const safeAvatar=allowedAvatars.includes(String(avatar))?String(avatar):'🦊';let assignedTeam=null;if(r.mode==='team'){const red=[...r.participants.values()].filter(p=>p.team==='red').length,blue=[...r.participants.values()].filter(p=>p.team==='blue').length;if(red<blue)assignedTeam='red';else if(blue<red)assignedTeam='blue';else assignedTeam=Math.random()<0.5?'red':'blue';}const p={id:s.id,nickname:String(nickname||'Player').trim().slice(0,20)||'Player',avatar:safeAvatar,team:assignedTeam,score:0,combo:0,maxCombo:0,eliminated:false,reconnectToken:token,disconnectedAt:null};
 r.participants.set(s.id,p);if(r.mode==='speedrun'&&r.phase==='speedrun'){p.speedIndex=0;p.speedStartedAt=Date.now();p.speedHistory=[];p.speedFinished=false} s.join(r.code);s.data.roomCode=r.code;s.data.reconnectToken=token;
 s.emit('player:joined',{code:r.code,nickname:p.nickname,avatar:p.avatar,title:(await getQuiz(r.quizId)).title,reconnectToken:token});
 broadcast(r);await syncPlayer(s,r);
});
s.on('host:start',()=>{const r=rooms.get(s.data.roomCode);if(r&&s.data.host&&r.phase==='lobby')startQuestion(r)});
s.on('host:skip',async()=>{const r=rooms.get(s.data.roomCode);if(!r||!s.data.host)return;if(r.phase==='question'){clearTimeout(r.nextTimer);await reveal(r)}else if(r.phase==='reveal'||r.phase==='between'){clearTimeout(r.revealTimer);const q=await getQuiz(r.quizId);if(r.questionIndex+1<q.questions.length){r.phase='between';io.to(r.code).emit('question:nextPreview',{index:r.questionIndex+1,total:q.questions.length,question:pubQ(q.questions[r.questionIndex+1])});broadcast(r);r.revealTimer=setTimeout(()=>startQuestion(r),50)}else finish(r)}});
s.on('player:answer',async({answer},ack)=>{const reply=(v)=>{if(typeof ack==='function')ack(v)};const r=rooms.get(s.data.roomCode);if(!r||r.phase!=='question'||!r.participants.has(s.id))return reply({ok:false,error:'문제가 이미 종료되었습니다.'});
const player=r.participants.get(s.id);if(player?.eliminated)return reply({ok:false,error:'서바이벌에서 탈락했습니다.'});if(r.mode==='speedrun')return handleSpeedAnswer(r,s,answer,reply);if(r.phase!=='question')return reply({ok:false,error:'지금은 답안을 제출할 수 없습니다.'});const q=(await getQuiz(r.quizId)).questions[r.questionIndex];const old=r.answers.get(s.id);if(old&&!q.allowAnswerChange)return reply({ok:false,error:'이미 제출한 답안입니다.'});const elapsed=Date.now()-r.startedAt,limit=Math.max(1,+(q.timeLimit||15))*1000;if(elapsed>=limit)return reply({ok:false,error:'제출 시간이 종료되었습니다.'});const is=correct(q,answer);let points=0;if(is){const ratio=Math.max(0,1-Math.min(elapsed,limit)/limit);points=Math.round((500+500*ratio)*(q.platinum?3:q.fever?2:1));if(q.highRisk&&player.riskChoice==='challenge')points*=2}else if(q.highRisk&&player.riskChoice==='challenge'){points=-Math.round((500+500*Math.max(0,1-Math.min(elapsed,limit)/limit))*(q.platinum?3:q.fever?2:1))}r.answers.set(s.id,{answer,correct:is,points,basePoints:points,elapsed,scoreCommitted:false});reply({ok:true,changed:!!old});s.emit('answer:locked',{ok:true,changed:!!old});if(r.hostId)io.to(r.hostId).emit('host:answers',[...r.answers.entries()].map(([playerId,a])=>({playerId,nickname:r.participants.get(playerId)?.nickname||'Player',...a})));broadcast(r);maybeReveal(r,q)});
async function handleSpeedAnswer(r,s,answer,reply){const q=await getQuiz(r.quizId);const p=r.participants.get(s.id);if(!q||!p||r.phase!=='speedrun'||p.speedFinished)return reply({ok:false,error:'이미 완료했거나 게임이 종료되었습니다.'});const qu=q.questions[p.speedIndex];const elapsed=Date.now()-p.speedStartedAt;if(elapsed>=Math.max(1,+(qu.timeLimit||15))*1000)return reply({ok:false,error:'제출 시간이 종료되었습니다.'});const is=correct(qu,answer);const limit=Math.max(1,+(qu.timeLimit||15))*1000;let points=is?speedPoints(elapsed,limit,qu):0;const row={index:p.speedIndex,correct:is,elapsed,points};p.score+=points;p.speedHistory.push(row);reply({ok:true,correct:is,points,elapsed});io.to(p.id).emit('speedrun:result',{index:p.speedIndex,correct:is,points,elapsed,nextIndex:p.speedIndex+1});p.speedIndex++;sendSpeedQuestion(r,p,q);broadcast(r)}
s.on('speedrun:timeout',async({index})=>{const r=rooms.get(s.data.roomCode);if(!r||r.phase!=='speedrun')return;const p=r.participants.get(s.id);if(!p||p.speedFinished||p.speedIndex!==Number(index))return;const q=await getQuiz(r.quizId);const qu=q?.questions?.[p.speedIndex];if(!qu)return;p.speedHistory.push({index:p.speedIndex,correct:false,elapsed:Math.max(1,+(qu.timeLimit||15))*1000,points:0});p.speedIndex++;sendSpeedQuestion(r,p,q);broadcast(r)});s.on('question:riskChoice',({choice})=>{const r=rooms.get(s.data.roomCode);if(!r||r.phase!=='riskChoice'||!r.participants.has(s.id))return;const p=r.participants.get(s.id);p.riskChoice=choice==='challenge'?'challenge':'coward';s.emit('question:riskChoiceAck',{choice:p.riskChoice})});
s.on('question:timeoutCheck',async({index})=>{try{const r=rooms.get(s.data.roomCode);if(!r||r.phase!=='question'||r.questionIndex!==Number(index))return;const q=(await getQuiz(r.quizId))?.questions?.[r.questionIndex];if(!q)return;const limit=Math.max(1,+(q.timeLimit||15))*1000;if(Date.now()-r.startedAt>=limit){clearTimeout(r.nextTimer);await reveal(r)}}catch(e){console.error('TIMEOUT WATCHDOG ERROR',e)}});
s.on('disconnect',()=>{const r=rooms.get(s.data.roomCode);if(!r)return;if(r.hostId===s.id){io.to(r.code).emit('error:msg','주최자가 나가서 방이 종료되었습니다.');rooms.delete(r.code);return}const p=r.participants.get(s.id);if(p){p.disconnectedAt=Date.now();setTimeout(()=>{const cur=r.participants.get(s.id);if(cur&&cur.disconnectedAt&&Date.now()-cur.disconnectedAt>=60000){r.participants.delete(s.id);r.answers.delete(s.id);broadcast(r)}},60000)}broadcast(r)})});
app.use((req,res)=>res.sendFile(require('path').join(__dirname,'public','index.html')));
init().then(()=>server.listen(PORT,'0.0.0.0',()=>console.log('QUIZ LIVE ONLINE on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
